### ISSUE TITLE
システムダイアグラム上のRTCが消えない、OpenRTPが固まる

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#1]
システムダイアグラム上にRTCを表示している状態でRTCのプロセスを終了させるとOpenRTPが固まる、もしくはシステムダイアグラム上にRTCが残り続ける現象が発生します。

対象：RELENG_1_2ブランチ

**Comment by n-ando** [comment]
Issue closeed
