### ISSUE TITLE
Add "const" to C++ RTC template code generated by RTCBuilder

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#111]
**Describe the bug**

https://github.com/OpenRTM/OpenRTM-aist/pull/522
に関連して、RTCのcppのCXX_RTC.cpp.vslにおて、<コンポーネント名>_specにconstをつける。

**Expected behavior**
```C++
static const char* analyzer_spec[] =
```
が、以下のようにconst付きで生成されてほしい

```C++
static const char* const analyzer_spec[] =
```

**Comment by n-ando** [comment]
この変更を適用すると、1.XのOpenRTMではコンパイルできないので、2.0まで保留する。

**Comment by n-ando** [comment]
修正お願いします。

**Comment by n-kawauchi** [comment]
この修正をmasterブランチに入れて頂いてOKです。
