### ISSUE TITLE
RTC Builderが生成するTravis設定ファイルの修正

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#116]
**Is your feature request related to a problem? Please describe.**
RTC Builderが生成するTravis設定ファイルには以下の問題を修正する必要がある。

- 実行環境がUbuntu 12.04、14.04と古いのでUbuntu 16.04、18.04に更新する
- テストを実行するようにする

**Describe the solution you'd like**
上記の通り。

**Describe alternatives you've considered**
以下にC++、Python用のサンプルを用意したので、この通りに修正する。Javaは当面は修正しない。

- [XXX.zip](https://github.com/OpenRTM/OpenRTP-aist/files/3372101/XXX.zip)
- [XXXpy.zip](https://github.com/OpenRTM/OpenRTP-aist/files/3372201/XXXpy.zip)

**Additional context**
以下に主な修正内容を記載する。

### C++、Python共通
- Ubuntu 16.04、18.04はDocker上で実行するため、Dockerの設定ファイルを作成する必要がある。scriptsフォルダを参照。
- サンプルでXXX、XXXpyと記載している箇所は作成するコンポーネントの名前に置き換える。

### C++
- テストがC++11でしかビルドできないため、`test/src/CMakeLists.txt`に修正が必要。以下の記述を追加。

```CMake
set_property(TARGET ${PROJECT_NAME}Test PROPERTY CXX_STANDARD 11)
```

### Python
- CMakeLists.txtに修正を加える必要がある。まず`idl/CMakeLists.txt`の内容はPythonでは不要のため全削除。サンプルの通りに記述する。

XXXpy直下のCMakeLists.txtに以下の記述を追加する。

```CMake
option(BUILD_IDL "Build and install idl" ON)
```

```CMake
if(BUILD_IDL)
    add_subdirectory(idl)
endif(BUILD_IDL)
```

CMakeLists.txtの以下の記述は削除する。

```CMake
set(IDL_FILES ""
              MyService.idl
)
```

```CMake
if(WIN32)
    set(SCRIPT_FILE ""
                    idlcompile.bat delete.bat)
else()
    set(SCRIPT_FILE ""
                    idlcompile.sh)
endif()
```

```CMake
install(DIRECTORY idl DESTINATION "${INSTALL_PREFIX}"
        COMPONENT component)
```

```CMake
set(EXEC_FILES ""
               XXXpy.py
               ${SCRIPT_FILE}) #${SCRIPT_FILE}を削除
```
### ビルドの確認
可能であればTravis CIでビルドが成功することを確認してからレビューを開始するようにする。
ビルドの確認が難しい場合は応相談。

手順は以下の通り。
まず、以下のようにGitHubのリポジトリを新規作成してRTC Builderで生成したコードをコミットする。

- https://github.com/Nobu19800/testRTC_CPP
- https://github.com/Nobu19800/testRTC_Py

Travis CIにログインする。

- https://travis-ci.org

操作画面の`+`をクリックしてリポジトリを追加する。

![image](https://user-images.githubusercontent.com/6216077/60877162-3a55fd80-a278-11e9-8025-e429166a4b00.png)

`More options`の`Trigger build`を押すか、Githubのリポジトリのファイルを更新するとビルドを開始する。

![image](https://user-images.githubusercontent.com/6216077/60877251-6d988c80-a278-11e9-8533-7dffacadba79.png)

**Comment by ga-sakamoto** [comment]
ルートディレクトリに含まれている以下のファイルは生成不要
 - README.md
 - memo_conan.md
