### ISSUE TITLE
IDLファイルのインストール先を変更した場合の影響について

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#119]
Linux環境でIDLファイルのインストール先を変更した場合の、RTCBuilder への影響について確認させて下さい。　https://github.com/OpenRTM/OpenRTM-aist-Java/issues/22 に対する修正検討です。
Javaで必要なidlのパスは ${RTM_JAVA_ROOT}/rtm/idl で、具体的なパスは、/usr/lib/x86-64-linux-gnu/openrtm-1.2/rtm/idl 等です。 

現在 idl はopenrtm-dev パッケージに含まれているので、切出して idl ファイルのみのパッケージを作成することになりました。　これに伴い、これまでのインストール先は、/usr/include/openrtm-1.2/rtm/idl でしたが、/usr/share/openrtm-1.2/idl とした場合の動作を確認することとなりました。rtm のサブフォルダを含めない点がポイントですが、　/usr/share/openrtm-1.2/rtm/idl とした場合と比較して影響の違いがあるかどうかも確認する予定でおります。

動作確認は、OpenRTP が見ているパスを変更する必要があると考えております。どこを修正したらよいのか教えて頂けますでしょうか。
なお、Windows環境での変更はございません。　よろしくお願いいたします。

**Comment by ga-sakamoto** [comment]
ご質問の本質を理解できていないかもしれませんが，OpenRTPでは明示的にidlのパスは見ていなかったと思います．${RTM_JAVA_ROOT}の参照先が変更となるだけでしたら，影響がないのではないか？と思います．

**Comment by n-kawauchi** [comment]
お手数をおかけしました。起動スクリプトopenrtpの中でidlのパスを取得しておりましたので、OpenRTP本体には影響なく動作確認できそうです。ありがとうございました。
