### ISSUE TITLE
RTCBuilderの「基本」タブ・カテゴリに列挙するRTCのカテゴリリストを作成する

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#135]
**Is your feature request related to a problem? Please describe.**

RTCBuilderの「基本」タブ・カテゴリには現在何もリストが入っていないが、ここに列挙するRTCのカテゴリリストを作成する。
InputDevice, Camera, Manipulator, Mobilebase, Planner, など。

**Comment by Nobu19800** [comment]
ImageProcessiong
Mobile Robot
Manipulator
Navigation
Sensor
Mobile Manipulator
Vehicle
Humanoid
Legged Robot
Quadruped Robot
Monitoring system
Image Sensor
Actuator
Motion Capture
Industrial Robot
Deep Learning
Game Engine
Office Suite
Manufacturing System
Autonomous Decentralized System
Cooperative Control
Reinforcement Learning
Genetic Algorithm
Multi-Robot
Controller
Medical Robot
Welfare Robot
Sound Sensor
Temperature Sensor
Acceleration Sensor
Gyro Sensor
Entertainment Robot
Social Robot
Graphical User Interface
Gamepad
Joystick
Transport System
Rescue Robot
Teaching Method
Omnidirectional Robot
Speech Synthesis
Omni-Directional Vehicle
Service Robot
Flying Robot
Teaching Materials
Educational Tool
Underwater Robot
Pet Robot
Force Sensor
Torque Sensor
Distance Sensor
Fuzzy Control
Neural Network
Laser Range Scanner
GPS
Geomagnetic Sensor
PID Controller
Simulator
Impedance Control
Force Control
Inverse Kinematics
Trajectory Tracking Control
Master-Slave
Disturbance Observer
Nonholonomic System
Ubiquitous Robot
Pneumatic Actuator
Hydraulic Actuator
Robust Control
Graphics Tablet
Virtual Reality
Augmented Reality
Database
Mixed Reality
Substitutional Reality
Motion Control
Motion Planner
Object Recognition
Walk Controller
Depth Camera
Mapping
Compliance Control
Speech Recognition
Speech Processing
Script Engine
Calibration
Sample
Test
Graph Visualization Tool
Computer Algebra System
Converter
Electromyograph
Telexistence Robot
Haptics
Dual Arm Robot
Web Application Server
Chatbot
Touch Sensor
Color Sensor
Agricultual Robot
Space Robot
Streaming
Animation
InputDevice

**Comment by ga-sakamoto** [comment]
｢基本｣タブの｢カテゴリ｣の部分なのですが，基本的にはコンボボックスで選択する形になっております．このため，階層化を行う事はできません．
また，上記100種類のアイテムをデフォルトでコンボボックスに設定する形で良いのでしょうか？
(選択が難しいように感じたため，ご確認させて頂きました)

**Comment by Nobu19800** [comment]
すみません。上のコメントは@n-ando さんに確認するために書いたものです。
階層化しているのは例えばセンサーのコンポーネントを作成した場合にカテゴリ名を単純に「Sensor」にするのか、それとも具体的に「Touch Sensor」「Color Sensor」とするのかについてまだ考えていないためです。これが「Sensor」にするのであれば、「Touch Sensor」等のカテゴリ名は無くなるため上に列挙しているよりもカテゴリ名の種類は減る予定です。

**Comment by n-ando** [comment]
多いので、トップレベルのみアルファベット順でプルダウンに入れることにしましょう。
