### ISSUE TITLE
RTCBが生成するREADME.＜CompName＞をREADME.mdとし、記載内容を検討する→RTCBへ組み込む

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#137]
**Is your feature request related to a problem? Please describe.**
RTCBが生成するREADME.＜CompName＞をREADME.mdとし、記載内容を検討する→RTCBへ組み込む

**Comment by Nobu19800** [comment]
こんな感じでどうでしょうか？

- https://github.com/Nobu19800/testRTC_CPP/blob/master/README.md

説明はファイル内のコメントに記述してあります。

- https://raw.githubusercontent.com/Nobu19800/testRTC_CPP/master/README.md

**Comment by ga-sakamoto** [comment]
申し訳ございません．できましたら画像ファイルの出力は行わない形とさせて頂けませんでしょうか？

また｢データポート｣の｢意味｣，｢サービスインターフェース｣の「引数」「戻り値」「例外」「事前条件」「事後条件」，「コンフィギュレーション｣の｢データ範囲｣につきまして，｢何を書くのか不明｣とのコメントが記載されておりますが，これらの項目は，そもそも必要でしょうか？(宮本さんが｢不明｣と言われるという事は，そもそも不要な要素なのでは？と思ったため，ご確認させて頂きました)

更に，｢RT-Component Configuration Parameter｣の内容は，rtc.confに出力される｢システム・パラメータ｣という意味だったと思います．こちらにつきましても必要でしょうか？

そして，｢Setup｣｢Usage｣｢Running the tests｣の部分に記載されているコメントの内容は出力する必要がございますでしょうか？

**Comment by Nobu19800** [comment]
画像ファイルについては難しいようであれば出力はしなくても結構です。
「何を書くのか不明」と書いた部分については、@n-ando さんでないと項目を設定した意図が分からないので必要かどうかも判断できません。

｢RT-Component Configuration Parameter｣の内容もReadme.mdに記載をお願いします。

｢Setup｣｢Usage｣｢Running the tests｣については空白にしてください。
