### ISSUE TITLE
MANIFEST.MFファイル中のバージョン番号を更新する

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#141]
**Describe the bug**
- MANIFEST.MFファイル中のバージョン番号は、ソースビルドスクリプト実行時、versionファイルで定義しているバージョン番号で書き換えている
- これはバージョン番号更新時、versionファイルのみ変更すれば済むという対応だが、従来から一部のMANIFEST.MF中のバージョン番号を更新する設定が抜けていたので、この部分のバージョン番号のみソースを更新している（後日、MANIFEST.MFのテンプレート化を予定していたため、最低限の修正で対応していた）
- これにより、masterソースの MANIFEST.MFファイルには、バージョン番号1.2.0と2.0.0が混在しており、RELENG_1_2ソースのMANIFEST.MFファイルには、バージョン番号1.2.0と1.2.1が混在しているが、ソースビルドスクリプトを実行すれば規定のバージョン番号に統一される
- ここで言うソースビルドとは、OpenRTPのWindows用msi生成のためのマージモジュール作成、及び、Linux用インストールパッケージを作成する際のビルドを指している

- 一方、OpenRTPのプラグイン開発時は、上記ソースビルドスクリプトを実行しないため、MANIFEST.MFファイルは更新されない
- masterとRELNEG_1_2ブランチを切り替えて、それぞれ用の修正を行う場合、MANIFEST.MFファイル中のバージョン番号を手動で更新しないとビルドが通らない状況になっている
- この不具合のため、MANIFEST.MFファイル中のバージョン番号をmasterブランチは2.0.0、RELENG_1_2ブランチは1.2.1とし、別のバージョン番号が混在しないように対応する

**Environment**
 - OS: Windows10
 - OpenRTM-aist Version 1.2.1と 2.0.0

**Comment by ga-sakamoto** [comment]
このIssueはこちらで修正してしまって良いのでしょうか？

**Comment by n-kawauchi** [comment]
はい、結構です。
1.2.1のリリース作業を優先しているため、着手できずにおりました。
よろしくお願いいたします。
