### ISSUE TITLE
「発生頻度、周期」、「処理速度、周期」等の説明を追加

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#148]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

RTC Builderの以下の設定項目についてヒントがないため説明を追加する。

- データポート -> Documentationの内容すべて
- コンフィグレーション -> Documentationの内容すべて
- コンフィグレーション -> RT-Component Configuration Parameter

**Describe alternatives you've considered**

**Additional context**

**Comment by ga-sakamoto** [comment]
以下のような説明でよろしいでしょうか？

○データポート
- 概要説明 : データポートに対する概要説明を記述します。
- データ型 : データポートの扱う型に対する説明を記述します。
- データ数 : データが配列になる場合など、データ数に関する説明を記述します。
- 意味 : データの意味の説明を記述します。
- 単位 : データ単位に関する説明を記述します。
- 発生頻度・周期 : データの発生頻度、周期に関する説明を記述します。
- 処理速度，周期 : データの処理速度、処理周期に関する説明を記述します。

○コンフィギュレーション・セット
- データ名 : ユーザ定義コンフィギュレーション・パラメータの名称に対する説明を記述します。
- デフォルト値 : ユーザ定義コンフィギュレーション・パラメータのデフォルト値に対する説明を記述します。
- 概要説明 : ユーザ定義コンフィギュレーション・パラメータに対する概要説明を記述します。
- 単位 : ユーザ定義コンフィギュレーション・パラメータの単位に対する説明を記述します。
- データ範囲 : ユーザ定義コンフィギュレーション・パラメータのデータ範囲に関する説明を記述します。
- 制約条件 : ユーザ定義コンフィギュレーション・パラメータの制約条件に関する説明を記述します。

○RT-Component Configuration Parameter
- Configuration : 設定を行うコンフィギュレーション名です。一覧から選択します。
- デフォルト値 : 設定対象コンフィギュレーションのデフォルト値です。予めデフォルト値が設定されている項目については、名称選択時にデフォルト値が設定されます。

**Comment by n-ando** [comment]
ヒントは以下のように変更をお願いします。

- データポート
  - 概要説明 : データポートに対する概要説明を記述します。
  - 意味→詳細説明 : データポートが出力する・受け取るデータの詳細説明を記述します。
  - データ型 : データポートの扱う型に対する説明を記述します。
  - データ数 : データが配列になる場合など、データ数に関する説明を記述します。InPortの場合は受け取ることができるデータ数、OutPortの場合は出力される可能性のあるデータ数についての参考情報を記載します。
  - 単位 : データのフィールドごとの単位に関する説明を記述します。
  - 発生頻度・周期 : OutPortが出力するデータの発生頻度、周期に関する説明を記述します。
  - 処理速度・周期 : InPortが受け取るデータの処理速度、処理周期に関する説明を記述します。

- コンフィギュレーション・セット
  - データ名 : コンフィギュレーション・パラメータの意味を表す名称を記述します。
  - デフォルト値 : コンフィギュレーション・パラメータのデフォルト値とその説明を記述します。
  - 概要説明 : コンフィギュレーション・パラメータに関する概要説明を記述します。
  - 単位 : コンフィギュレーション・パラメータの単位に関する説明を記述します。
  - データ範囲 : コンフィギュレーション・パラメータのデータ範囲に関する説明を記述します。  主に連続値をとるパラメータの場合記載します。
  - 制約条件 : コンフィギュレーション・パラメータの制約条件に関する説明を記述します。主に離散値をとるパラメータの場合に記載します。

RT-Component Configuration Parameter については削除
