### ISSUE TITLE
RTC Builderで記入方法が分かりづらい項目の記入例をヒントに記載する

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#150]
**Is your feature request related to a problem? Please describe.**
RTC Builderの以下の項目について何を記入するのかよく分からない

- コンフィグレーション -> Documentation -> データ範囲
- サービスポート -> 引数、戻り値、例外
- データポート -> 意味、発生頻度・周期、処理速度・周期

**Describe the solution you'd like**
ヒントに記入例を記載する。

**Describe alternatives you've considered**

**Additional context**

**Comment by n-ando** [comment]
- データポート
  - Documentatioin
    - 概要説明：データポートが取り扱うデータの意味の概要説明を記載。
    - データ型：データポートのデータ型を記載。
    - データ数：配列型などの場合のデータ数の制限を記載。
    - 意味：データの型の意味およびコンポーネントにおけるデータの意味を記載。
    - 単位：データポートのデータの単位を記載。
    - 発生頻度・周期：ポートがOutPortの場合はそのデータの発生頻度（突発的、平均〇秒に1回）やその周期（〇Hz等）を記載
    - 処理速度・周期：ポートがInPortの場合はそのデータの発生頻度（突発的、平均〇秒に1回）やその周期（〇Hz等）を記載
- サービスポート
  - Documentation（インターフェース） 
    - 引数：関数ごとの引数の意味を記載。例：関数名0(速度[6], 位置[6]), 関数名1(位置姿勢), ... 
    - 戻り値：関数ごとの戻り値の意味を記載。例：リターンコード  = 関数名0(), 位置 = 関数名1(), ... 
    - 例外：関数ごとの例外の意味を記載。関数名0(): (例外：ファイルが見つからない、引数条件違反), 関数名1(): （例外：一範囲エラー）
    - 事前条件：関数ごとの事前条件の意味を記載。関数名0：事前条件、関数名1：事前条件
    - 事後条件：関数ごとの事後条件の意味を記載。関数名0：事後条件、関数名1：事後条件
- コンフィグレーション
  - Documentation
    - データ名: データの名称。データの意味を端的に表す名称を指定。
    - デフォルト値：データのデフォルト値とその意味を記載。
    - 概要説明：データの意味の概要説明を記載。
    - 単位：データの単位を記載。
    - データ範囲: データがとりうる連続値の範囲を記載。
    - 制約条件：データが特定の値や制約条件（列挙型指定、配列指定、ハッシュ型指定等）を持つ場合はその条件を記載。
