### ISSUE TITLE
RT System Editorで全てのRTCについて状態検出方法を設定できるようにする

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#159]
※この変更については@n-ando さんに確認をしていないため、承認後に作業を開始してください。

**Is your feature request related to a problem? Please describe.**
#156 で個別にRTCの状態検出方法を設定できるようになったが、RTCをシステムダイアグラム上に出した時点でオブザーバーが登録されるため、グローバルに設定をできるようにしたい。

**Describe the solution you'd like**
RTC全体で状態検出方法を設定するトグルボタンを追加する。
そのトグルボタンによりRTCがデフォルトで状態検出をオブザーバかポーリングかを使うか選択可能にする。
個別に設定するトグルボタン(#156 )のOn/Offは、何もしなければRTC全体のトグルボタンのOn/Offと同じにする。
個別に設定するトグルボタン(#156 )を操作すると、対象のRTCについては状態検出方法が切り替わる。

RTC全体のトグルボタンのOn/OffはRT System Editorを終了、起動しても終了前と同じOn/Offの状態になるようにする。

**Describe alternatives you've considered**

**Additional context**

**Comment by n-ando** [comment]
ボタンは
- オブザーバグローバル設定トグルボタン
- オブザーバRTC毎設定トグルボタン
を分けてツールバーに追加することで坂本さんにお願い。アイコンは安藤が作成します。
