### ISSUE TITLE
idlcompileの可搬性

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/OpenRTP-aist#173]
Windows上で独自IDLを含むPythonのRTCを生成したところ，idlcompile.shの内容は以下のようになりました．
```
#!/bin/sh
omniidl -bpython -I"C:\Program Files\OpenRTM-aist\1.2.0\rtm\idl" idl/FingerVision.idl 
```
これでは，そのままLinuxで使えません．そこまで可搬性を想定していないということでしょうか？

**Comment by n-kawauchi** [comment]
申し訳ございません。リリース予定のOpenRTM-aist 1.2.1版では改善されております。
1.2.1版msiでインストールしたWindows環境でPython RTCを生成しますと、idlcompile.sh は下記となります。
```
#!/bin/sh
IDL_PATH=`rtm-config --rtm-idldir`
omniidl -bpython -I$IDL_PATH idl/CalibrationService.idl 
```
このIDL_PATH指定のコマンドをLinuxで実行しますと、下記のパスを取得できます。
```
$ rtm-config --rtm-idldir
/usr/include/openrtm-1.2/rtm/idl
```
よろしくお願いいたします。

**Comment by y-masutani** [comment]
回答ありがとうございます．
1.2.1で解消とのこと了解いたしました．
