### ISSUE TITLE
RTCB: README.md テンプレートアップデート（FSM関連）

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#177]
README.md テンプレートのFSM関連項目の追加およびアップデートを行う。

**Comment by n-ando** [comment]
@Nobu19800  本件よろしくお願いいたします。

**Comment by Nobu19800** [comment]
以下のようにサンプルを作成しました。確認をお願いします。

- https://github.com/Nobu19800/testRTC_CPP/blob/master/README.md#eventports-definition
- https://raw.githubusercontent.com/Nobu19800/testRTC_CPP/master/README.md
