### ISSUE TITLE
RTCB: doc/index.txt テンプレートアップデート（FSM関連）

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#178]
doc/index.txt テンプレートのFSM関連項目の追加およびアップデートを行う。

**Comment by n-ando** [comment]
@Nobu19800  本件よろしくお願いいたします。

**Comment by Nobu19800** [comment]
以下のようにサンプルを作成しました。ご確認をお願いします。

- https://github.com/Nobu19800/testRTC_CPP/blob/master/doc/content/index.txt#L111-L136
- https://github.com/Nobu19800/testRTC_CPP/blob/master/doc/content/index_j.txt#L103-L128
