### ISSUE TITLE
RTC Builderの生成するCMakeLists.txtでfind_package(OpenRTM)としているのは何故か？

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#179]
RTC Builderで生成したCMakeLists.txtでOpenRTMのライブラリを検出する部分は以下のようになっている。

```
find_package(OpenRTM)
```

`OpenRTM`の後ろに`REQUIRED`を付けるとOpenRTMは必須ライブラリとなり見つからなかった場合にエラーになりますが、RTC Builderで生成するコードではOpenRTM-aistが見つからなくても進むことになります。これは何か意図があるのでしょうか？

**Comment by ga-sakamoto** [comment]
CMakeLists.txtの内容につきましては，ご提供いただきました内容を出力するようにしております．
ご連絡を頂きました部分につきましても，上記の形式でご連絡を頂きましたため，現在のような出力内容となっております．

**Comment by n-ando** [comment]
requiredをつけるように修正してください。
