### ISSUE TITLE
サービスポートのインターフェース型にManipulatorCommonInterface_CommonやManipulatorCommonInterface_Middleを指定すると***_idl_example.pyを生成しない

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#181]
**Describe the bug**
RTC Builderで以下の条件でコード生成すると`***_idl_example.py`を生成しない。

* サービスポートのインターフェース型に`JARA_ARM::`からはじまる名前を指定する
* 言語はPythonを指定する
* 方向にProvidedを指定する

**To Reproduce**
上記の通り。

**Reproducibility**
100％

**Expected behavior**
`***_idl_example.py`を生成するようにする。RELENG_1_2にも変更を反映する。

**Screenshots or Logs**

**Environment**
 - OS:  Windows 10
 - OpenRTM-aist 1.2

**Additional context**

**Comment by n-kawauchi** [comment]
@ga-sakamoto さん
このIssueの RELENG_1_2 に対するPR作成をお願いします。
