### ISSUE TITLE
.appveryor.ymlを変更していないのに結果比較の画面が出てくる

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#193]
**Describe the bug**
`.appveryor.yml`を変更していないのにコード生成で結果比較の画面が表示される。

![image](https://user-images.githubusercontent.com/6216077/65213748-5977d380-dae2-11e9-8a88-904e604f704b.png)

**To Reproduce**
1. RTC Builderでコード生成する
2. 再度コード生成する

**Reproducibility**
100％

**Expected behavior**
変更をしていないのに結果比較画面を出さないようにする。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 2.0

**Additional context**

**Comment by Nobu19800** [comment]
申し訳ありません。#174 で改行コードが変わっていたので発生しなくなっていたようです。このIssueは閉じます。

**Comment by ga-sakamoto** [comment]
かしこまりました．
ただ，こちらでも同様な現象は発生しておりましたので，念のため#194の方をマージさせて頂ければ幸いです．
