### ISSUE TITLE
Activate Systemsボタン、Deactivate Systemsボタンの動作について

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#200]
Activate Systemsボタンを押したときに既にアクティブ状態のRTCが存在すると`事前条件が不正です`というメッセージが出ます。
「システムダイアグラム上の全てのRTCをアクティベートする」という機能という事だったので、この動作が仕様通りかもしれないのですが、使いづらいです。

「Activate Systemsボタンを押したときに既にアクティブ状態のRTCが存在した」という事をユーザー側が知ることによって、何か得をする場合があるのでしょうか？

**Comment by n-ando** [comment]
エラーメッセージを出ないように変更してください。
