### ISSUE TITLE
FSM用エディタが編集ボタンを押した回数だけウィンドウが増える？

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#209]
**Describe the bug**
#95 、#96 でFSMエディタが複数回起動する問題は解決したはずなのですが、今動作確認すると何故か複数起動する。

**To Reproduce**
1. RTCBのFSMタブの編集ボタンを数回押す

**Reproducibility**

**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist master branch

**Additional context**
こちらの環境の問題の可能性もあるため、動作確認をして問題がなければこのissueは閉じてください。

**Comment by n-ando** [comment]
#211 で解決したのでクローズします。
