### ISSUE TITLE
[RTCB]rtc.confの出力内容を修正

### ISSUE THREAD

**Issue by ga-sakamoto** [OpenRTM/OpenRTP-aist#239]
RTCBuilderで生成するrtc.confの内容を，最新版のOpenRTM-aistで使用する内容に修正する

**Comment by ga-sakamoto** [comment]
/etc/rtc.conf.sample の内容および /etc/component.confの内容を基に修正

**Comment by n-kawauchi** [comment]
この修正を1.2へも反映させて下さい。よろしくお願いします。
