### ISSUE TITLE
Transition Editorに入力した内容が消える

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#249]
**Describe the bug**
FSMエディタのTransition Editorでドキュメントに入力した内容が消えることがある。

**To Reproduce**
1. Transition Editorを開く
2. ドキュメントの概要説明などを入力する
3. OKを押してTransition Editorを閉じる
4. 再度Transition Editorを開く
5. ガード条件を設定する
6. OKを押してTransition Editorを閉じる
7. 再度Transition Editorを開くとドキュメントの内容が空欄になる

**Reproducibility**
100％

**Expected behavior**
ドキュメントの内容が消えないようにする。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist master branch

**Additional context**

**Comment by ga-sakamoto** [comment]
こちらのご指摘なのですが，現状のFSMエディタでは，エディタ内で定義した状態，遷移に不変の一意IDを割り当てる事ができません．
(RTCBuilderとFSMエディタの間で，commons-scxml-0.9.jarというライブラリを使用しているためです)

このため，遷移につきましては，｢遷移元状態｣｢遷移先状態｣｢ガード条件｣の情報を使用して，識別を行っております．
従いまして，｢ガード条件｣が変更されてしまうと，マッチングが取れなくなってしまい，過去の情報が消えてしまいます．

どうにかできないか色々と検討を行ったのですが，上記のjarファイル内のコードを修正しないと対応できなかったため，現状では上記のような実装となっております．

**Comment by n-ando** [comment]
本件、容易に解決できないみたいなので、保留にしておきます。
