### ISSUE TITLE
RTSystemEditor起動中にネットワークが変わった場合に動作が不安定になる

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#252]
**Describe the bug**
RT System Editor起動中に無線LANの接続先を切り替えるなどしてIPアドレスが変わった場合に、ポートの接続が失敗する、画面が固まるなどの不具合が発生する。

**To Reproduce**
1. RTSystemEditorを起動する
2. 無線LANの接続先を切り替える
3. RTSystemEditor上でデータポートを接続する

**Reproducibility**
100％

**Expected behavior**
RTCにコンポーネントオブザーバーを登録する際に、ネットワーク切り替え前の情報で登録しようとするため、到達不能なIPアドレスでアクセスしようとして問題が発生する。

以下のような対処法が考えられる。

1. RTSE側でネットワークの切り替えを検知して対処する
2. OpenRTM-aist側でコンポーネントオブザーバーをデフォルトでオフにする、もしくはコンポーネントオブザーバーの機能を削除する

コンポーネントオブザーバーはトラブルが多すぎるため、機能の削除がいいと思います。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 1.2.1

**Additional context**

**Comment by n-ando** [comment]
@ga-sakamoto さん

- オブザーバをデフォルトでOFFに設定してください。
- RTSEで自IPアドレスが変更されたことを検知する方法についてご調査ください。
  - 検知したらダイヤログを出す
- CORBAの参照内のIPアドレスを変更する方法についてもご調査ください。

**Comment by n-kawauchi** [comment]
> オブザーバをデフォルトでOFFに設定してください。

@ga-sakamoto さん、この対応はどのようになっているのでしょうか？　1.2.2に関係するのか気になったのでお伺いしました。

**Comment by ga-sakamoto** [comment]
こちらの修正は現時点では未着手です．
また，1.2系に修正内容を反映するのかはお伺いしておりません．

**Comment by n-ando** [comment]
@ga-sakamoto  さん 1.2に反映する方向で修正お願いします。

**Comment by ga-sakamoto** [comment]
> - オブザーバをデフォルトでOFFに設定してください。

こちらの内容なのですが，オブザーバ使用のON/OFF設定は2.0で追加された機能となります．
このため1.2では，オブザーバの使用をOFFにする事ができません．
もしも1.2にも反映するのであれば，オブザーバ使用ON/OFF機能から移植する必要があり，結構大掛かりな修正となると思います．

**Comment by n-ando** [comment]
ネットワーク変更注意ダイアログは1.2にも入れてください。
CORBAの参照内のIPアドレスを変更する方法についての調査は別issueにします。
