### ISSUE TITLE
同じIDLファイルでも環境によって「IDLファイルのパースに失敗しました」のメッセージが出る場合がある？

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#254]
**Describe the bug**
独自データ型の定義に同じIDLファイルを使用しても、別の環境にIDLファイルをコピーするとRTCBuilderが「IDLファイルのパースに失敗しました」のメッセージを出す場合があるらしい。
またエラーメッセージが出ても定義したデータ型は表示される。

**To Reproduce**

- https://twitter.com/mute_mf/status/1202854244396613634

**Reproducibility**
自分の環境では再現できていません。

**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS: 不明
 - OpenRTM-aist 1.1.2

**Additional context**

**Comment by n-ando** [comment]
最近はこの現象は起きていないみたい。
また、1.2ではパース時に失敗した箇所の情報が出るので、同様の問題が起こったら再オープンすることとする。
