### ISSUE TITLE
LogViewの仕様を考える

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#273]
**Is your feature request related to a problem? Please describe.**
- OpenRTM-aistのFluent Loggerの仕様が1.2と2.0で異なるため対応する。もしくは2.0のみ対応して1.2には対応しないようにする。
- 指定レベルのログレベルのみを表示するようにしたい
- 蓄積したメッセージを削除できるようにしたい
- 出力したプロセス、ログメッセージの名前で分類できるようにしたい
- ログレベルで並び替えできるようにしたい
- ログを保存できるようにしたい

**Describe the solution you'd like**

**Describe alternatives you've considered**
- OpenRTM-aistのFluent Loggerの仕様が1.2と2.0で異なるため対応する。もしくは2.0のみ対応して1.2には対応しないようにする。
以下が(1) OpenRTM-aist 1.2 C++版のメッセージをTd-agentで受信して標準出力した例。
```
2020-02-03 16:47:06.000000000 +0900 fluent.test.follow: {"message":"2020-02-03 15:49:06,743 file.manager VERBOSE 0 components are marked as finalized.","time":"2020-02-03 15:49:06","level":"DEBUG"}
```

以下は(2) OpenRTM-aist 1.2 Python版、もしくは2.0 C++版、Python版の例。

```
2020-02-03 14:20:00.000000000 +0900 fluent.test.follow: test.simpleio: {"time":"2020-02-03 14:20:00,761","name":"fluent.manager","level":"VERBOSE","message":"0 components are marked as finalized."}
```

(1)にはJSON形式のレコード部分に`message`キーに時刻、ログの種類、ログレベルが含まれているが、(2)では時刻、ログレベルは削除、ログの種類は`name`キーに格納している。

OpenRTM-aist 1.2のdebパッケージには手違いによりFluent Loggerが入っていないらしいので、2.0のみの対応でも問題はないはず。

- 指定レベルのログレベルのみを表示するようにしたい
上記の通り、`level`キーによりログレベルを取得できるので、それで分類できる。
ログレベルごとにチェックボックスを配置して、チェックボックスがオンのログレベルのメッセージのみを表示する。

- 蓄積したメッセージを削除できるようにしたい
現状、メッセージを削除する機能がないようなのでボタンを押すと全削除するようにできるようにする。
- 出力したプロセス、ログメッセージの名前で分類できるようにしたい
まず、ログメッセージを以下のようなテーブルで表示できるようにする。

![image](https://user-images.githubusercontent.com/6216077/73642165-8d7c1b80-46b4-11ea-9c8a-54683f831253.png)

識別子の項目には上記のレコードの`name`キーの値を入力する。
ログを出力したマネージャ名は現状取得できないため、今後OpenRTM-aistに機能を追加する。
現在の検索機能のようにマネージャ名、識別子をテキストボックスに入力して分類できるようにする。

- ログレベルで並び替えできるようにしたい
上記のテーブルのログレベルのセルをクリックすることでログレベルが高い方から、もしくは低い方から並び替えできるようにする。

- ログを保存できるようにしたい
FluentdではInputプラグインで拾ったログをOutputプラグインに流すことができるが、influentの仕様が不明のため調査が必要。

**Additional context**
この変更は@n-ando さんが確認していないため、問題がないことを確認してから作業を行う。

**Comment by n-ando** [comment]
OKです。
