### ISSUE TITLE
FSMコンポーネントを設定した場合、エラーになるPythonコードを生成することがある

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#275]
**Describe the bug**
RTCBuilderでFSMポートを設定してPythonのコードを生成すると、以下のように何も定義していないクラスを定義してしまい実行時にエラーになる。

```Python
@StaticFSM.FSM_SUBSTATE(Top)
class node2(StaticFSM.Link):
```

**To Reproduce**
1. RTC BuilderでFSMポートを設定する
2. あるノード(以下node1)で`Actions`の`On Entry`、`On Exit`のチェックボックスをオフにする
3. node1に遷移を設定するがイベント名は設定しない
4. 生成したPythonコードを実行する

もしくは単に`final node`を追加するだけでも問題を再現できる。

**Reproducibility**
100％

**Expected behavior**
上記の設定のノード(`ActionsのOn Entry、On Exitのチェックボックスをオフにする`、`遷移を設定するがイベント名は設定しない`)がある場合は、対応するクラスに`pass`の記述を追加する。

```Python
@StaticFSM.FSM_SUBSTATE(Top)
class node2(StaticFSM.Link):
    pass
```

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 2.0

**Additional context**

**Comment by ga-sakamoto** [comment]
#277 にて，onInit関数をコメントアウトせずに出力する事となったため，上記のようなコードが生成されることはなくなったためクローズ
