### ISSUE TITLE
FSMコンポーネントのonInit関数はどうすれば有効化できるのか？

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#277]
FSMエディタのState Editorには`On Entry`と`On Exit`のチェックボックスはありますがonInit関数を有効にする方法が分かりません。

onInit関数に対応したチェックボックスを配置しないのであれば、onInit関数はデフォルトで有効にするべきでは？

**Comment by n-ando** [comment]
生成されるコード上で、onInit()はデフォルトで有効になるようにしてください。

**Comment by ga-sakamoto** [comment]
念のためのご確認です．
onInit関数につきましては，以前のお打ち合わせでご確認させて頂いた際に，｢使用する場合にはユーザがコメントアウトを外す形にする｣となり，敢えてコメントアウトした形で出力しているのですが，こちらの仕様が変更になった，と思って良いでしょうか？

**Comment by n-ando** [comment]
説明コメントを追加して、デフォルトで有効にしてください。

The onInit method provides a special kind of entry action. On state transition, onEntry functions are called at the target state and its superstate. But an onInit function is called only at the target state.
