### ISSUE TITLE
RTSystemEditorでSave Asでファイル名の指定ができない。

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/OpenRTP-aist#287]
**Describe the bug**
UbuntuでOpenRTPを実行し、RTSystemEditorを起動して作業をして何等かの手順で「Save As」を選らんで開くダイアログから「参照」ボタンを押すとダイアログを開いた場合、そのダイアログにファイル名を指定する場所がないのでファイル名が指定できないため、既存のファイルへの上書きしかできない。(前もって空ファイルを作るか）参照せずにファイルを指定するしかない。

**To Reproduce**
Ubuntu 18.04でOpenRTPをインストールし、それが使える環境で
1. ターミナルを開く
2. openrtpと入力しEnterキーを押す
3. ワークスペースの選択等をしてOpenRTPを起動する
4. パースペクティブから[RT System Editor]を選び、RTSystemEditorを起動する。
5. 上方のアイコンメニューより[Open New System Editor]をクリックし、新規System Editorを開く
6. 中央に開いたSystem Diagramを右クリックし[Save As...]を選ぶ
7. 開いたダイアログの[参照]ボタンを押す
8. 開いたダイアログにファイル名を指定する入力ボックスがないことを確認する

同様に18.04では[ファイル(F)]メニューから[別名保存]を選んで、[参照]ボタンを押しても同じようにファイル名を指定することができません。(16.04ではなぜか上部のテキストベースのメニューが表示されなかったので確認ができてません。)

Windows 10の環境では同じ操作をした場合、ファイル名が入力できるダイアログが表示されます。

**Reproducibility**
100%

**Expected behavior**
最後に開くダイアログのどこかにファイル名を入力する入力ボックスが表示される。

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment**
 - OS: Ubuntu 16.04 32bit/Ubunt 18.04 
-- Windows 10では問題ない
 - OpenRTP Version 1.2.1
 
**Additional context**

**Comment by ga-sakamoto** [comment]
手順8で開いたダイアログ上にて，以下の操作ではファイル名を指定できませんでしょうか？
- 画面左側の｢場所｣一覧で，｢ファイル・システム｣など，｢検索｣｢最近開いたファイル｣以外を選択
- 左上のアイコン(｢ファイル名を入力してください｣)を選択し｢場所｣を表示
- ｢場所｣に対象ファイル名を設定

**Comment by n-kawauchi** [comment]
> 左上のアイコン(｢ファイル名を入力してください｣)を選択し｢場所｣を表示

このアイコンは見当たりません。　お手数をおかけして申し訳ございませんが、キャプチャ画面を貼り付けていただけますでしょうか。　よろしくお願いします。

**Comment by ga-sakamoto** [comment]
![FileSave](https://user-images.githubusercontent.com/45808384/77384176-0d2a8a80-6dc8-11ea-8cb8-0061d9c8f054.png)
左上の鉛筆のようなアイコンです．
クリックすると｢場所｣というエリアが表示されました．

**Comment by n-kawauchi** [comment]
Ubuntu18.04ではないですよね？　OpenRTPはaptでインストールされましたか？
こちらでの Ubuntu18.04でaptでインストールした環境では下記ダイアログになります。

![openrtp121+ubuntu1804](https://user-images.githubusercontent.com/19547996/77388245-e4f45900-6dd2-11ea-9471-4a18ad2dcc2e.png)

**Comment by ga-sakamoto** [comment]
こちらで試したのはUbuntu16.04となります．

なお，対象のダイアログは，Eclipseが提供している標準のダイアログを使用しております．
｢Other Locations｣やその左の｢+｣ボタンをクリックしたり，右クリックメニューなどで，新規ファイルを作成できませんでしょうか？

**Comment by n-kawauchi** [comment]
Ubuntu18.04では新規ファイルを作成できません。　下記の状況です。　対応可能でしょうか。
https://sicklylife.hatenablog.com/entry/2018/07/15/232709

**Comment by ga-sakamoto** [comment]
もしもこちらで対応しようとすると，Eclipse SWTで提供されているダイアログを再実装することとなってしまいますため，できれば避けたいです．
ご紹介頂いたページの後半に記載されている対応策を行った場合でも現象は改善されませんでしょうか？

**Comment by ga-sakamoto** [comment]
なお，IssiueではUbuntu16.04でも18.04でも×となっていますが，16.04の方は上記の方法でOKと思って良いでしょうか？

**Comment by n-kawauchi** [comment]
上記ページの 「touch ~/Templates/空のドキュメント」を実行すると、記載通りに空のドキュメントは作成できるようになります。　しかし、Save As... で開いたダイアログで「参照」をクリックした時に開くダイアログ（↑のキャプチャ画面）では変わりありません。　

先ほどUbuntu16.04で確認した場合も同様で、坂本さんのキャプチャ画面のようには表示されませんでした。

坂本さんの方で対応されないとなると、あらかじめ空ファイルを作成しておくか、参照せずに保存ファイルのフルパスを指定する手順になりますね。

**Comment by ga-sakamoto** [comment]
｢参照｣ボタンクリック時に表示されるファイル選択ダイアログ起動時のオプションを修正してみたソースをPR #292 に上げてみました．
たいへん申し訳ございませんが，こちらを使用して再度試してみて頂けませんでしょうか？

**Comment by n-kawauchi** [comment]
ありがとうございます。動作OKでした。
#292 のソースからdebパッケージを作成・インストールしての確認です。masterブランチへの修正でしたので、RELENG_1_2への修正もお願いします。

Save As... で開くダイアログの「参照」を押してファイル名を入力できるようになりました。保存したxmlファイルを、「Open and Restore...」で復元でき、RTCのポート間が接続される動作も確認できました。

![openrtp200+ubuntu1804](https://user-images.githubusercontent.com/19547996/77398654-4b857100-6deb-11ea-9b62-a5471e3d7719.png)

**Comment by ga-sakamoto** [comment]
ご確認，ご連絡ありがとうございます．
また，色々とご面倒をお掛けしてしまい申し訳ございませんでした．
RELENG_1_2に対して修正を行ったものをPR #293 として上げさせて頂きました．
