### ISSUE TITLE
データポート接続時、シリアライザ選択時の動作の仕様を考える

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#295]
**Is your feature request related to a problem? Please describe.**
- システムエディタ上の操作で異なるデータ型のInPortとOutPortを選択してコネクタを生成できないが、独自シリアライザで通信可能な場合は接続できるようにしてほしい

**Describe the solution you'd like**
ポートプロファイルの`dataport.marshaling_types`の値から特定のシリアライザを使うと通信可能かを判定して異なるデータ型のポートでも接続可能にする。

**Describe alternatives you've considered**
InPort、OutPortの接続について以下の5種類の状況が考えられる。

- (A) InPortとOutPortのデータ型が同じの場合

![image](https://user-images.githubusercontent.com/6216077/78014870-7fc8d680-7383-11ea-9e78-2de2b585e0af.png)

- (B) InPort側で独自デシリアライザが使える場合

![image](https://user-images.githubusercontent.com/6216077/78009273-c0bced00-737b-11ea-9c11-0b816babfa4a.png)

-(C) OutPort側で独自シリアライザが使える場合

![image](https://user-images.githubusercontent.com/6216077/78195630-219f0f00-74bb-11ea-81eb-1c8c756de219.png)

-(D) OutPort、InPortの両方で独自シリアライザ、デシリアライザが使える場合

![image](https://user-images.githubusercontent.com/6216077/78009420-f5c93f80-737b-11ea-8082-7aad741a82ca.png)

-(E) cdr以外のシリアライザを使用可能な場合

![image](https://user-images.githubusercontent.com/6216077/78009457-05488880-737c-11ea-8f26-79f38c44beb6.png)

まず(A)については従来通りシステムダイアグラム上でデータ型を比較して接続可能にする。

(D)については、使用可能なシリアライザから以下の`シリアライザの種類`、`符号化後のデータ型(複合前のデータ型)`が一致した場合に接続可能にする。

シリアライザの命名規則を以下に示す。

- OutPort側
![image](https://user-images.githubusercontent.com/6216077/78011343-6c673c80-737e-11ea-9299-0e95e1286bd3.png)

- InPort側
![image](https://user-images.githubusercontent.com/6216077/78015145-f1a12000-7383-11ea-9f5a-1ac1bdb3cfa5.png)

![image](https://user-images.githubusercontent.com/6216077/78012761-6e31ff80-7380-11ea-996e-f08011b51761.png)

(B)についてはさらに2種類の状況が考えられる。

- (1) シリアライザ、デシリアライザの名前のどちらにも`符号化後のデータ型(複合前のデータ型)`が含まれている場合

この場合は(D)と同様に`シリアライザの種類`、`符号化後のデータ型(複合前のデータ型)`を比較して判定する。

![image](https://user-images.githubusercontent.com/6216077/78012771-72f6b380-7380-11ea-987a-f38876575917.png)

- (2) シリアライザ、デシリアライザの名前のどちらかに`符号化後のデータ型(複合前のデータ型)`が含まれていない場合

この場合については`シリアライザの種類`の比較はできるが、`符号化後のデータ型(複合前のデータ型)`の比較ができない。

![image](https://user-images.githubusercontent.com/6216077/78012963-b94c1280-7380-11ea-88b3-b3282b58f57b.png)

`符号化後のデータ型(複合前のデータ型)`を省略している場合、ポートプロファイルから取得できるポートのデータ型と`符号化後のデータ型(複合前のデータ型)`は同一であるため、ポートプロファイルから取得したデータ型と比較する。

![image](https://user-images.githubusercontent.com/6216077/78013278-38414b00-7381-11ea-937a-239e5cd1dbeb.png)

(C)についても同様に処理する。

(E)については(D)と同様に`シリアライザの種類`、`符号化後のデータ型(複合前のデータ型)`を比較して判定する。

![image](https://user-images.githubusercontent.com/6216077/78015287-2f05ad80-7384-11ea-8ca0-795d3696daa3.png)

接続するポートのシリアライザの名前を全て比較して、上記の方法で接続可能かを判定する。

- コネクタプロファイル設定画面について

コネクタプロファイルの設定画面でポートを通信可能にするシリアライザの名前のみ表示するのが理想であるが、例えば以下のように通信可能にするシリアライザが複数存在し、組み合わせ次第で通信可能できない場合に問題になる。

![image](https://user-images.githubusercontent.com/6216077/78195580-f3213400-74ba-11ea-91ff-b8103f887290.png)

この場合に`OutPort Serializer`のコンボボックスで選択したシリアライザと対応するデシリアライザを`InPort Serializer`に自動的に表示するという処理が必要になり難しくなるため、現行通り使用可能なシリアライザ、デシリアライザは全て表示するようにする。

ただし、`Serializer Type`に表示する項目は現状では`シリアライザの種類`を比較して`シリアライザの種類`をドロップダウンリストに表示するようになっているが、単純にInPortとOutPortのシリアライザの名前を比較して一致したものを表示するだけに変更する。

**Additional context**
この修正内容は@n-ando さんに確認を取っていないため、指示を受けてから作業を行う。

**Comment by Nobu19800** [comment]
上記の動作確認には以下にアップロードした`serializer_sample.zip`を使用する。

- https://github.com/OpenRTM/OpenRTM-aist/pull/839

**Comment by n-ando** [comment]
1.  現在dataport.data_type が一致した時のみポートの接続が可能になっていますが、この判断をこのissueのロジックに変更してください。
2. ConnectorProfileのダイアログの表示の変更
2.1 シリアライザ指定プルダウンには、cdr + rosなど他のシリアライザがあればそれらを表示
2.2 cdrのみ、詳細指定なしても接続可能
2.3 cdr以外は、詳細指定が必要
3. 詳細指定ダイアログ
3.1 左に側にOutPort, 右側にInPortのプルダウン
3.2 プルダウンには、選択可能なシリアライザを列挙
3.3 選択時に接続可能せいは、赤文字でステータスバーに表示

以上のように変更をお願いいたします。＞ @ga-sakamoto

**Comment by ga-sakamoto** [comment]
@Nobu19800 様
サンプルRTCおよび実行用バッチファイルなどのご作成ありがとうございました．
ただ，たいへん申し訳ございませんが，(B)の(1)に該当するサンプルがどれになるのかがわかりませんでした．

**Comment by ga-sakamoto** [comment]
@Nobu19800 様
何度も申し訳ございません．
もしも可能であれば，｢コネクタプロファイル設定画面について｣に記載のある｢接続可能｣｢接続不可｣が混在したサンプルにつきましてもご提供頂けませんでしょうか？

**Comment by Nobu19800** [comment]
以下のようにサンプルを追加しました。

- https://github.com/OpenRTM/OpenRTM-aist/pull/844

**Comment by ga-sakamoto** [comment]
早速のご対応ありがとうございました．
