### ISSUE TITLE
1.2と2.0のRTCを接続するとsubsc typeに1.2でサポートしないtypeが現れる

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#312]
**Describe the bug**

1.2と2.0のRTCを接続するとsubscription typeに1.2でサポートしないtypeが現れる。

**Expected behavior**

PortProfileが申告するSubscription typeは
- 1.2: flush, new, periodic
- 2.0: block, flush, new, nonblock, periodic
が設定されているが、両者のANDをとって、ConnectorProfileダイヤログには  { flush, new, periodic } のみ表示されるべき。

その他のPortProfileについても、同様に両者のANDを表示するかどうかアルゴリズムを見直す。

**Environment**
 - OS: Mac OS X (RTC 1,2, 2.0), Windows (RTSE 1.2.1)

**Comment by ga-sakamoto** [comment]
現状のアルゴリズムなのですが，基本的にはInPortの設定とOutPortの設定でAndを取る形になっております．ただ，Anyが設定されている場合には，相手側の情報を全て表示してしまいます．
このため，subscription typeとして
 - 2.0版RTC : block, flush, new, nonblock, periodic
 - 1.2版RTC : Any

という設定の場合に，block, flush, new, nonblock, periodicが表示されてしまいます．

こちらはどのように修正すればよろしいでしょうか？

**Comment by n-ando** [comment]
すみません、勘違いしてました。InPortのSubscription Typeは常にAnyでしたね。
正しい動作ですので問題ございません。申し訳ありません。
クローズします。
