### ISSUE TITLE
RTC.xmlが正常に保存できない

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#315]
**Describe the bug**
1. コード生成したときにRTC.xmlが保存されていないことがある
2. RTC.xmlを保存しようとしたときに以下の画面が表示される場合がある
![image](https://user-images.githubusercontent.com/6216077/82802679-3e076880-9eba-11ea-8f72-a305b581e3fe.png)

**To Reproduce**
1. RTCBuilderでコンポーネント名等を入力
2. コード生成ボタンを押す
3. 1の問題発生
4. RTC.xmlを編集
5. Ctrl+Sでファイルを保存
6. 2の問題発生

**Reproducibility**
100％

**Expected behavior**
正常に保存できるようにする

**Screenshots or Logs**

**Environment**
 - OS: Windows
 - OpenRTM-aist master branch

**Additional context**

**Comment by n-ando** [comment]
再現条件を詳しく教えてください。

**Comment by Nobu19800** [comment]
手順が抜けていました。
コンフィギュレーションパラメータを設定すると保存できないエラーが出るみたいです。

**Comment by n-kawauchi** [comment]
この修正はmasterブランチだけが対象ですか？　1.2へも反映させるならばPRの作成をお願いします。

**Comment by ga-sakamoto** [comment]
今回の修正内容は，FSM4RTC対応に関連した部分となります．
このため1.2には影響しません

**Comment by n-kawauchi** [comment]
了解しました。　頂いたお返事から、1.2にも関係するIssueは必ずPRを作成していると受けとめました。リリースを控えているので、更新を気にしております。

**Comment by ga-sakamoto** [comment]
> 頂いたお返事から、1.2にも関係するIssueは必ずPRを作成していると受けとめました。

申し訳ありません．そういう意味ではありません．
単純に，今回のIssueはFSM4RTC対応の際に追加したソースで発生した問題なので，1.2では(この追加ソースが存在しないため)影響はない内容です．という意味です．

各Issueの修正内容を1.2にも反映させるかどうかにつきましては，これまで各Issue毎にご指示を頂いていたかと思います．

**Comment by n-kawauchi** [comment]
>各Issueの修正内容を1.2にも反映させるかどうかにつきましては，これまで各Issue毎にご指示を頂いていたかと思います．

打合せに同席しておりませんので、Issueについては @ga-sakamoto さんが一番ご存じだとの認識でおります。1.2への反映も必要かどうか確認して一緒に対応して頂けると助かります。よろしくお願いいたします。

**Comment by ga-sakamoto** [comment]
次回お打ち合わせ時に，安藤さんと相談させて頂きます．
