### ISSUE TITLE
RTSE/RTCBの高解像度アイコンを作成し組み込む

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#317]
Eclipseのアイコンの件についてです．

その後，更に調べてみた所，
Eclipse4.6から，ファイル名に「@2x」を付加し既存のアイコンと同じディレクトリに配置することで，高解像度の際にアイコンが切り替わる仕組みが追加されたようです．
(@2xのアイコンは32x32が使用できるようです)

https://www.eclipse.org/eclipse/news/4.6/platform.php
https://www.eclipse.org/eclipse/news/4.6/platform_isv.php

ただ・・・こちらのディスプレイで試してみた所，
解像度が足りないせいかアイコンが切り替わるのを確認できませんでした．
(16x16の内容とは全く異なるアイコンを32x32で作成し，
 @2xを付加してみたのですが，元のアイコンが表示されてしまいました)

たいへん申し訳ございませんが，32x32のアイコンを作成して頂き，
上記の手順で切り替わるかどうかをお試し頂けませんでしょうか？
ご面倒をお掛けしてしまい，たいへん申し訳ございませんが，
よろしくお願いいたします．

**Comment by h8892-inaba** [comment]
<img width="964" alt="32p-img" src="https://user-images.githubusercontent.com/38091038/84981203-f1d4de80-b16e-11ea-989f-a2311f1fbcdc.png">
