### ISSUE TITLE
Ubuntuで起動した際「LoadableModules」ボタンに文字が収まらない

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#334]
- 6/9更新ソース（4b654a4）から作成したdebパッケージでインストール（Ubuntu18.04上）しての確認です
- マネージャコントロールビューの[Loadable Modules]ボタンに文字が収まりません。下図参照 
 - Windows環境（最新の1.2.2-Beta200611版msi使用）では収まっています。
- また、画面上部のアイコン（ALL Activate Systems等）がだいぶ右寄りに表示されます。これはWindows環境でも同様です。4/6更新ソース（7e76018）から作成したWindowsインストーラで確認した場合、アイコンは正しく左寄りで表示されます。
- 1.2に関するPRが全て反映されるとこの問題は解決しますでしょうか？

![OpenRTP_4b654a4](https://user-images.githubusercontent.com/19547996/84738521-02594d80-afe5-11ea-854d-9c601fa39a98.png)

**Comment by ga-sakamoto** [comment]
画面上部のアイコンの位置なのですが，Eclipse内での設定が変わってしまったようで，現状では右端に表示されてしまいます．
表示位置の指定を削除する事で，左側に移動する事もできるのですが，この場合，以下の図のようにエディタを開くボタンよりも左側となってしまいます．
![ToolBar](https://user-images.githubusercontent.com/45808384/85035788-861a6200-b1be-11ea-92fc-43d8002c2821.png)
もしもこの形でも良いようでしたら，修正したソースをコミットさせて頂きます．
更に細かい位置の調整が必要でしたら，調査を行ってみますので，しばらくお時間を頂ければ幸いです．

なお，以前は明示的に表示位置を指定していたのですが，これを行うとRCP化した際に正常に表示されない，という報告がございましたため，表示位置の指定方法を元に戻した結果となります．

[Loadable Modules]ボタンの件につきましては，システムアイコンのサイズ設定に依存してしまうと思うのですが，どれくらいボタン幅を広げれば良いでしょうか？
(現状のXX倍くらいというご指示を頂ければ，その内容で修正させて頂きます)

**Comment by n-kawauchi** [comment]
昨日生成した下記のWindows用全部入りパッケージで起動しましたが、表示されているアイコンが @ga-sakamoto さんと異なります。　下図がこちらでの確認ですが、エディタを開くアイコンは見当たらないように思えます。
eclipse473-openrtp122v20200618-ja-win32.zip

![openrtp122v20200618](https://user-images.githubusercontent.com/19547996/85083684-69594b00-b20d-11ea-8a1f-280f261f4a1f.png)

[Loadable Modules]ボタン幅についての指示は @n-ando さんに判断を頂きますので、お待ちください。

**Comment by ga-sakamoto** [comment]
エディタを開くアイコンですが，左側から４番目，５番目のON,OFFという文字が書かれたアイコンとなります．

**Comment by n-kawauchi** [comment]
>エディタを開くアイコンですが，左側から４番目，５番目のON,OFFという文字が書かれたアイコンとなります．

失礼いたしました。了解です。
今回の1.2への修正が入る直前の 4/6更新ソース（7e76018）でのアイコンの位置はこれまで通りの左よりの表示でした。この間にEclipse内での設定が変わるということがあるのでしょうか？

**Comment by ga-sakamoto** [comment]
昨日も記載させて頂きましたが，4/6更新ソースでは，ツールバー上での表示位置を明示的に指定しておりました．しかし，この指定を行うとRCP化した際に正常に表示されない，という連絡がありました．
このため，ツールバー上での表示位置の指定方法を，Eclipseで一般的に使用されている方法に戻したのですが，このデフォルトの表示位置が変更となっておりました．

ご質問の意図としては，元の表示位置(左よりの表示)に修正せよ，という意味と思ってよろしいでしょうか？

**Comment by n-kawauchi** [comment]
>4/6更新ソースでは，ツールバー上での表示位置を明示的に指定しておりました．しかし，この指定を行うとRCP化した際に正常に表示されない，という連絡がありました．

申し訳ございません。ようやく確認しました。確かにRCP版のみ表示が右寄りになっていました。
この情報を認識できておらず、なんどもお手数をおかけしてしまいました。
最終判断は @n-ando  さんが下されますので、お待ちください。

**Comment by n-ando** [comment]
[Loadable Modules]ボタンの幅の件ですが、どのOSでも、文字の幅に合わせてボタンの幅を調整いただけないでしょうか？
普通ボタンはラベル文字の幅に合わせて適当に幅調整をしてくれないのでしょうか？

**Comment by n-ando** [comment]
ECボタン、Activate/Deactivateボタンは、少なくともパースペクティブボタンより右に配置されると、みな違和感を持つと思いますので、On/Offよりも右、パースペクティブより左の位置が適切かと思いますのでそのようになるよう修正をお願いします。

**Comment by n-kawauchi** [comment]
@ga-sakamoto さん、「C:\Users\ユーザ名\\.eclipse」下を削除すると、Activate/Deactivateボタン等がOn/Offより右側に表示されることを、私と @h8892-inaba さんの環境で確認できました。
（#336 のコメント）　参考になるかもしれないと思い、お知らせしました。

**Comment by n-ando** [comment]
@ga-sakamoto さん
ボタンの幅の変更は他のGUI要素に影響がありそうなので、ボタンのラベルを、

- Loadable Mod.
- Loaded Mod.

に変更してください。
