### ISSUE TITLE
RTSystemEditorスプラッシュウインドウが表示されない

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#337]
RTSystemEditorスプラッシュウインドウが表示されない。

**Comment by ga-sakamoto** [comment]
スプラッシュウインドウはjp.go.aist.rtm.systemeditor.RCPプロジェクト内のsplash.bmpを使用しております．
こちらのファイルがJARファイル内に含まれていないのではないでしょうか？

**Comment by n-kawauchi** [comment]
確認したところ、OpenRTM 1.1.2版のmsiに含まれるRCP版RTSEの起動では、確かにスプラッシュウィンドウが表示されます。
jarファイルは、「jp.go.aist.rtm.systemeditor.RCP_1.0.0.jar」(2011/07/20) でして、jar -xvf で展開すると、確かにsplash.bmpが含まれていることを確認できます。この当時は関わっていなかったので、ビルド詳細が分かりません。

次にリリースしたOpenRTM 1.2.0版に含まれるRCP版RTSE作成は担当しましたが、この「jp.go.aist.rtm.systemeditor.RCP_1.2.0.jar」（2018/04/18）には splash.bmp が含まれません。ビルド手順は Redmine の wiki に書かれていた手順に従いました。
この説明中、splash.bmp に関する記述は見当たりません。
https://openrtm.org/redmine/projects/rtsystemeditor/wiki/RCP版RTSystemEditorの作成手順

splash.bmp を含めるためには、どこを修正したらよいのか見当が付きません。ご存じでしたら @ga-sakamoto さんにお願いしたいと思います。

**Comment by ga-sakamoto** [comment]
上記のページがいつ書かれたものなのかわからないのですが･･･
splash.bmp を含める手順なのですが，大きくは２カ所かと思います．
- jp.go.aist.rtm.systemeditor.RCPプロジェクトのbuild.propertiesにsplash.bmpが含まれているか？
- 対象ファイルをチェックアウトした際に，splash.bmpが含まれているか？
まずはこちらをご確認頂けませんでしょうか？
(現状，手元の環境ではRCP版の作成を行う事ができないので)

**Comment by n-kawauchi** [comment]
> jp.go.aist.rtm.systemeditor.RCPプロジェクトのbuild.propertiesにsplash.bmpが含まれているか？

下記ファイルのことですね。含まれておりません。
https://github.com/OpenRTM/OpenRTP-aist/blob/RELENG_1_2/jp.go.aist.rtm.systemeditor.RCP/build.properties

subversion の rtmtools の trunkソースを確認しましたが、このbuild.propertiesは 2013/3/17 に @ga-sakamoto さんが追加されており、その時から設定内容が変わっていないとの認識です。
