### ISSUE TITLE
ポート、RTCの名前が表示されない

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#34]
**Describe the bug**
以下のようにポートやRTCの名前が表示されなくなることがある。もしかすると、RTSystemEditor側ではなくEdgeRTCが原因かもしれない（下記参照）が、EdgeRTC自体はポートが消えた後でも動き続けているため、RTSystemEditor型の問題の可能性が濃厚。

![image](https://user-images.githubusercontent.com/6216077/56478504-e47c7f80-64ea-11e9-8f13-bb1563113e19.png)

**To Reproduce**
再現性の有無は今のところ不明だが、以下の手順でRTC同士を接続しActivateたところ、RTSystemEditor上からポートが消え、ブロックの長方形のみのRTCになる。なお、この状態でRTCをクリックすると、ポートなどがないRTCProfileが右のビューに表示される。

* Windows上で1.2のOpenCVCameraRTC、CameraViewerRTCを起動
* Linux上で1.1.2のEdgeRTCを起動
* Windows上のRPC版RTSystemEditorでRTC間のポートを接続
* Activateすると、エディタ上のEdgeRTCのポートアイコンが消え、Profile上もポートがないRTCのように見える
* ただし、接続は維持されており、画像表示も継続される。
* この現状はEdgeRTCでのみ発生している？（Hough, Rotate, Flipなどでは発生せず。）
* Activate時？に以下のメッセージがEdgeRTCのコンソールに表示される。

`omniORB: To endpoint: giop:tcp:[::ffff:10.211.55.10]:53406. System exception MARSHAL(YES,MARSHAL_MessageSizeExceedLimitOnClient) while (un)marshalling. Send GIOP 1.2 MessageError.`

**Reproducibility**
上記の環境では100％再現する。
他の組み合わせについてはまだ試していない。

**Expected behavior**
たとえ、1.1.2のRTCとの組み合わせでも、RTSYSTEMEDITOR側では正しく表示されるべき。

**Screenshots or Logs**

**Environment**
実行環境について加筆をお願いします。
 - OS: Ubnutn 16.04 64bits, Windows 10 64bit
 - OpenRTM-aist Version 1.1.2 (Ubuntu), 1.2 (Windows)

**Additional context**

**Comment by n-ando** [comment]
EdgeRTC側で、CORBAのExceptionのWarningが出ているのですが、調べてもらえますか？＞宮本君

**Comment by Nobu19800** [comment]
1.1.2ではOutPortのプロファイルに送信データを格納する機能があったはずです。
Edgeコンポーネントの場合、RTSEでコンポーネントプロファイルを取得する際に3つ分の送信データを格納した情報を取得することになるため、640×480の画像だとomniORBのデフォルトの制限を超えてしまいます。1.1.2の問題の原因の大半はこの機能が原因のためまず疑ったほうがいいです。
1.2ではこの機能自体削除されているので問題は発生しません。IssueのCloseをお願いします。

**Comment by n-ando** [comment]
RTSEが原因ではないのでcloseします。
