### ISSUE TITLE
OpenRTP 1.2.1 on Linuxでコード生成ボタンが押せない問題

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#354]
**Describe the bug**
OpenRTP 1.2.1/1.2.2 on Linuxでコード生成ボタンが押せない
データポートがあるとエラーダイアログが表示され、この症状が出現する模様。

**Reproducibility**
不明

**Environment**
 - OS: Ubnutn 18.04 64bits
 - OpenRTM-aist Version 1.2.1/1.2.2

**Comment by Nobu19800** [comment]
idlファイルに追加した` #pragma keylist TimedRGBColour`の行でパースのエラーが発生しているようです。

```
jp.go.aist.rtm.rtcbuilder.corba.idl.parser.TokenMgrError: Lexical error at line 180, column 4.  Encountered: "p" (112), after : "#"
```

`#pragma`から始まる行を無視するようにしてもらわないと解決しません。
