### ISSUE TITLE
doxyfile.in にnkfは不要かどうか調査

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#361]
**Is your feature request related to a problem? Please describe.**

- doxyfile.in にnkfは不要かどうか調査
- 不要なら、nkf -w コマンドを削除
- インストーラからnkfを削除

**Comment by n-ando** [comment]
1.2.2 Builderで生成したコードでは、UTF-8 のファイルしかなかった。(EUC, Shift-JISのファイルは無い）

**Comment by n-kawauchi** [comment]
この件ですが、ユーザが用意した Shift-JISのファイルが加わった時、生成されたdoxygenファイルが文字化けしていたので、
nkfの変換を加えたのが経緯です。（2017年の確認）

具体的には下記ソースコードで確認しています。ここではShift-JISのヘッダーファイルがいくつも追加されています。
https://github.com/Nobu19800/Foot_Position_Controller

この時、iconv利用の動作も試したが、元々がUTF-8のファイルに対して実行するとエラーになると分かり、文字コードが混在しているケースでは使えないと判断しています。

ユーザが追加したソースについて考慮しなくてよいならば、nkfは外せますね。

**Comment by n-ando** [comment]
調査ありがとうございました。

やはり、nkfの文字コード判別ロジックには一日の長がありますね。pythonにもnkfモジュールなるC言語モジュールがありpip でインストールできるようにもなっているようです。nkfはまだ現役っぽいのでそのまま維持したいと思います。

以下のライセンス文を添付してください。


Copyright (c) 1987, FUJITSU LTD. (I.Ichikawa).
Copyright (c) 1996-2018, The nkf Project.  https://osdn.jp/projects/nkf/

This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.

Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.

2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.

3. This notice may not be removed or altered from any source distribution.

**Comment by ga-sakamoto** [comment]
念のためのご確認なのですが，上記のライセンス文は，RTCBuilderで生成するコード内に含めるのでしょうか？
それとも，インストーラに含めるのでしょうか？

**Comment by n-kawauchi** [comment]
nkfはWindows用インストーラに同梱しているので利用許諾が必要となり、ライセンスファイルをインストーラ（msi）に含めます。RTCBuilderが生成したRTCは、nkf を使用しているだけですので、不要との認識です。

**Comment by ga-sakamoto** [comment]
かしこまりました．
ご説明ありがとうございました．
