### ISSUE TITLE
RTSProfileをロードしてrtcdでRTCが起動するか確認

### ISSUE THREAD

**Issue by n-ando** [OpenRTM/OpenRTP-aist#362]
**Is your feature request related to a problem? Please describe.**
2.0に向けて、RTSProfileからのRTCの自動起動の機能について確認する。

- RTSProfileをロード
- システムに含まれるRTCをどのノード (マネージャ) で起動するかのアサイン
  - 当該RTCが起動できるかをチェックする
  - どのスレーブマネージャで起動するかを指定することもある
- システムを起動する

などの機能が正しく動作するか確認する。

**Comment by ga-sakamoto** [comment]
上記の項目については，どれも実行可能である事を確認したため，一旦，クローズ
