### ISSUE TITLE
[RTCB] Linux環境でのアクティビティタブでON/OFFラジオボタン表示が分かりにくい場合がある

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#369]
**Describe the bug**
- Ubuntu20.04 + OpenRTP1.2.2 で発生、Ubuntu18.04 + OpenRTP1.2.2 では問題ない
- 新規RTC作成時、アクティビティタブにて onExecute等を有効にするためラジオボタンのONを押すが、選択されている状況が分かりづらい。Windowsと異なりラジオボタンの中央を黒くするのではなく、縁の線の太さを変えて選択されていることを示しているようだが、線の色が細い

![openrtp-activity](https://user-images.githubusercontent.com/19547996/98070998-bd578a00-1ea5-11eb-9364-65e5a00589fa.png)

- Ubuntu20.04環境でもconfigurationの選択でラジオボタンを使っている場合は、下記のように線が太く表示されるので、これと同じにした方がよいと思える
- Ubuntu18.04の上記アクティビティタブのラジオボタンは下記のように太く表示されるので問題ない

![configuration](https://user-images.githubusercontent.com/19547996/98071172-30610080-1ea6-11eb-9370-8b277bdb61b2.png)

**Reproducibility**
100%
Ubuntu20.04の２つの環境（実機とVM環境）で同じ状況を確認した

**Environment**
 - OS: Ubnutn 20.04 64bits
 - OpenRTM-aist Version 1.2.2

**Comment by sakamotog** [comment]
#370も同様なのですが，ツールを起動する前に，コンソールで以下を設定してみてください．
export SWT_GTK3=0

なお，今回ご指摘頂きました現象は，全てのラジオボタン，チェックボックスで発生しているようでした．

**Comment by n-kawauchi** [comment]
ありがとうございます。教えて頂いた手順で起動したところ改善しました。
openrtpの起動用シェルスクリプトに「export SWT_GTK3=0」を組み込む場合は、どういう条件で判断したらよろしいでしょうか。

**Comment by sakamotog** [comment]
少し調べてみた所，Ubunto20.04以外の場合でも，SWT_GTK3が｢0｣以外に設定されていると，同様な現象が発生するようです．このため，環境変数SWT_GTK3を確認して，これが｢0｣以外の場合には｢0｣に設定する形ではダメでしょうか？

**Comment by ga-sakamoto** [comment]
#370も同様なのですが，Ubuntu20.04で動作させる際には，ツールを起動する前に，コンソールで以下を設定してみてください．
export SWT_GTK3=0

なお，今回ご指摘頂きました現象は，全てのラジオボタン，チェックボックスで発生しているようでした．

**Comment by ga-sakamoto** [comment]
少し調べてみた所，Ubunto20.04以外の場合でも，SWT_GTK3が｢0｣以外に設定されていると，同様な現象が発生するようです．このため，環境変数SWT_GTK3を確認して，これが｢0｣以外の場合には｢0｣に設定する形ではダメでしょうか？
(アカウントがおかしかったので，再度，記載させて頂きました)

**Comment by n-kawauchi** [comment]
ありがとうございます。Ubuntu16.04，18.04，20.04で動作を確認してみます。
