### ISSUE TITLE
[RTCB] Python RTCのcmake policy設定を見直す

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#389]
**Is your feature request related to a problem? Please describe.**
- OpenRTP1.2.2でPython RTCを生成すると、CMakeLists.txtに下記ポリシーが定義される
```
if(POLICY CMP0040)
  cmake_policy(SET CMP0040 OLD)
endif()
if(POLICY CMP0053)
  cmake_policy(SET CMP0053 OLD)
endif()
```
- cpackでのパッケージ生成のためcmakeを実行すると、下記ワーニングが出る場合がある
  - Windows10 + cmake3.14.3 と Ubuntu20.04 + cmake3.16.3 で確認
  - Ubuntu18.04 + cmake3.10.2 ではCMP0053のみの確認で、ワーニングは出ない
- cmakeドキュメントによると、ポリシーのOLD動作は定義により非推奨になり、CMakeの将来のバージョンで削除される可能性があるとのこと
https://cmake.org/cmake/help/v3.16/policy/CMP0040.html
https://cmake.org/cmake/help/v3.16/policy/CMP0053.html
```
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_policy):
  The OLD behavior for policy CMP0040 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:6 (cmake_policy):
  The OLD behavior for policy CMP0053 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```

**Describe the solution you'd like**
- CMP0040 に関しては、add_custom_command の定義に関するもので、上記ポリシーを定義しないとエラーになる
- ImageProcessingのTkCalibGUIではCMP0040を定義していないので、このadd_custom_commandは参考になりそう

**Comment by ga-sakamoto** [comment]
こちらはどのように修正すればよろしいでしょうか？
cmake_policyの部分を全て削除する形になるのでしょうか？
また，mainとRELENG_1_2の両方で修正する必要がありますでしょうか？

**Comment by n-kawauchi** [comment]
修正方法についてはこれから検討する必要があるということで、Assigneesを自分にしました。
現時点の設定ではワーニングが出るということでRTCの起動には影響ありませんので、優先順位は高くありません。
修正方法が決まりましたらここへ追記します。　今のところ修正対象はmasterブランチのみになると考えています。

**Comment by n-kawauchi** [comment]
一番トップのCMakeLists.txtのcmake_policy（計6行）全てを削除してください。削除したソースで下記環境にてワーニングが出ないことを確認しました。
Windows10（cmake3.23.2）、Ubuntu20.04（cmake3.16.3）、Ubuntu22.04（cmake3.22.1）

合わせて「cmake_minimum_required(VERSION 2.8)」もワーニングがでますので、バージョン番号をC++と同じ3.5.1に修正してください。
