### ISSUE TITLE
OpenRTPのみをインストールした場合にeclipseが起動しない

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#39]
**Describe the bug**
インストーラーでOpenRTPのみをインストールした場合に以下のようにeclipseが起動しない。

![image](https://user-images.githubusercontent.com/6216077/57341272-b21e8380-7174-11e9-98f9-26ac1e34da21.png)

**To Reproduce**
1. インストール時にカスタムを選択する
2. OpenRTPのみを指定してインストールする
3. OpenRTPを起動する

**Reproducibility**
100％

**Expected behavior**
OpenRTPのみをインストールした場合でも起動できるようにする。
またはOpenRTPのみをインストールすることはできないようにする。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 1.2

**Additional context**

**Comment by n-kawauchi** [comment]
確認しました。　原因はシステム環境変数RTM_ROOTが定義されていないためでした。

対応としては、OpenRTPのみをインストールしても起動できるようにします。
カスタムインストール時に選択するツリー項目は、「表示する」「表示しない」のどちらかしか定義できず、「単独インストール時はツリーに表示しない」というような条件で動作を変えることができないためです。

**Comment by n-kawauchi** [comment]
msi生成用wxsにて対応完了。詳細は下記チケットに記載。
https://openrtm.org/redmine/issues/4661

OpenRTM-aist-1.2.1-Beta190703版のmsiにて動作OKでしたので、本Issueはcloseします。
