### ISSUE TITLE
FSMエディタで同一名のEventを複数定義した場合の動作について

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#395]
**Is your feature request related to a problem? Please describe.**
RTCBuilderのFSMエディタで以下のように同じ名前のEventを複数定義すると、出力したソースコードのTop状態で同一名の関数が宣言されてしまうためエラーになる。

![image](https://user-images.githubusercontent.com/6216077/106985755-5f408880-67ad-11eb-8924-63932835c0a4.png)

```CPP
  FSM_TOPSTATE(Top) {
    // Top state variables (visible to all substates)
  
    FSM_STATE(Top);

    // Machine's event protocol
    /*!
     */
    virtual void testevent() {}
    
    /*!
     */
    virtual void testevent() {}
```

**Describe the solution you'd like**
同一名のEventを定義していいのか仕様が不明のため、@n-ando さんに確認する。

- 同一名のEventを定義してはいけない場合
そもそも同一名のEventを定義してはいけないのであれば、FSMエディタでエラーにする。

- 同一名のEventを定義してもいい場合
同一名のEventを定義してもいいのであれば、Top状態のクラスで上記のtesteventというメンバ関数は1つしか宣言しないようにする。
以下のようにデータ型の設定が違う場合、引数が違う同一名のメンバ関数が宣言される。
Pythonでオーバーロードはできないため、同一イベントでデータ型の設定が違う場合はFSMエディタでエラーにする。

![image](https://user-images.githubusercontent.com/6216077/106992290-6d95a100-67bb-11eb-9a64-c1f610fa31a4.png)

```CPP
    virtual void testevent(RTC::TimedLong data) {}
    
    /*!
     */
    virtual void testevent() {}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by n-ando** [comment]
坂本さん、本件いかがでしょうか？
