### ISSUE TITLE
configurationダイアログの文字位置調整について

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#402]
Ubuntu環境でconfigurationダイアログを開くと項目名の文字列の最後が切れてしまいます。
Windows環境では表示されます。　これの調整は可能でしょうか。

具体的は下図の下から2番目の「exposure_mode」の最後の e が隠れてしまいます。
configuration viewでは表示されます。
Windows環境ではテキストボックスの位置は一番下の「exposure_absolute」の文字長に合わせて表示されるのでそろっています。

![OpenCVCamera_210301](https://user-images.githubusercontent.com/19547996/109459677-a1a27000-7aa2-11eb-9dd5-a2cedb870570.png)

![configuration-view](https://user-images.githubusercontent.com/19547996/109459721-b3841300-7aa2-11eb-8f95-5bc197602eef.png)

**Comment by ga-sakamoto** [comment]
現状のconfigurationダイアログでは，項目名部分の幅を100と設定しています．
この部分を設定しないと，以下のようにそれぞれ自動調整するようになります．
![image](https://user-images.githubusercontent.com/45808384/109986659-4b0a8f80-7d49-11eb-8052-3e7268973608.png)

ただ，この形にした場合，項目名が非常に長かった場合に，項目名の横幅が非常に長くなってしまうのですが，こちらは問題ございませんでしょうか？
(ダイアログ自体がリサイズ可能なので，上記の場合には横に伸ばして頂けば良いのかもしれませんが･･･)


もしくは，列幅は指定したままで，項目名が長かった場合に，以下のように改行させる事もできるようです．
![image](https://user-images.githubusercontent.com/45808384/109987762-41355c00-7d4a-11eb-8735-cb32a6f7ed3a.png)

どちらの形とすればよろしいでしょうか？

**Comment by n-ando** [comment]
150固定で、オーバーした場合は２行にする方法でお願いします。
