### ISSUE TITLE
[RTCB] ドキュメント生成タブで入力した作成者情報のソース挿入位置が異なる

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#426]
**Describe the bug**
- C++のRTC生成時の不具合です。　他の言語を指定した場合の動作は確認しておりません。
- ドキュメント生成タブで入力した作成者情報が、.cpp と .h ファイルで挿入位置が異なり、違和感があります 

**To Reproduce**
- C++のRTCを新規作成し、ドキュメント生成タブで作成者情報のみ入力しコード生成した結果は以下となります
- src下とtest下の各 .cpp ファイルは以下の様式で、これが基準と認識しています。
```
/*!
 * @file ModuleNameComp.cpp
 * @brief Standalone component
 * @date $Date$
 *
 * @author Noriaki Ando <n-ando@aist.go.jp>
 *
 * $Id$
 */
```
- これに対し、include下の .h ファイルは下記となっています。
```
/*! \mainpage
 *
 * @author Noriaki Ando <n-ando@aist.go.jp>
 *
 */
 
 /*!
 * @file  ModuleName.h
 * @brief ModuleDescription
 * @date  $Date$
 *
 * $Id$
 */
```
- test下の .h ファイルには挿入されません
```
/*!
 * @file  ModuleNameTest.h
 * @brief ModuleDescription
 * @date  $Date$
 *
 * $Id$
 */
```

**Reproducibility**
100%

**Environment**
 - OS: Ubnutn 18.04 64bits
 - OpenRTM-aist Version 2.0.0
 - OpenRTP-aist 2.0.0 (マージ待ちのPR423から全部入りパッケージを生成して使用）

**Comment by n-ando** [comment]
cppの方に合わせてください。
$Id$, $Date$ は削除してください。
テストコードのcpp/hには以下のコメントを追加してください。

```
/*!
 * @file ModuleNameComp.cpp
 * @brief Standalone component (test code)
 *
 * @author Noriaki Ando <n-ando@aist.go.jp>
 */
```
