### ISSUE TITLE
[RTCB] 複数のデータポート定義時、BuildViewで上から順番に描画されない

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#427]
**Describe the bug**
- データポートを複数定義すると、BuildView では下から積み上げるように描画される
- このため、BuildView でデータポートの位置を確認したRTCを実行すると、RTSEではデータポートの描画順番が反対になる
![data-port](https://user-images.githubusercontent.com/19547996/122698148-b25d3880-d281-11eb-9513-f72de3aa4521.png)
- BuildView でデータポートは定義した順番に上から描画されるようにする

**Reproducibility**
100%

**Environment**
 - OS: Ubnutn 18.04 64bits
 - OpenRTM-aist Version 2.0.0
 - OpenRTP-aist 2.0.0

**Comment by n-ando** [comment]
登録順に上から並べて表示してください。
