### ISSUE TITLE
FSMEditor上でのノード間接続操作が分かりにくい

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#48]
**Is your feature request related to a problem? Please describe.**
ノード間を接続する際、下図のようにノードの端と端を接続しようとしてしまし、できませんでした。
![connect_NG1](https://user-images.githubusercontent.com/19547996/57595750-d8cc2800-7581-11e9-9234-a292db330bda.png)

ノードの真ん中辺りをクリックして緑色の線が表示されたら、マウスを押したままドラッグすれば接続線が描画されると分かりましたが、相手ノードの真ん中にドラッグしないと、下図のように新たなノードが作成されてしまいます。
![connect_NG2](https://user-images.githubusercontent.com/19547996/57595832-52fcac80-7582-11e9-9078-2320df78217e.png)

**Describe the solution you'd like**

もっと簡単にノード間を接続できるように改善できますでしょうか？

**Comment by ga-sakamoto** [comment]
FSMEditorの部分につきましては，指定された外部ライブラリを使用しているため，操作方法などはそちらで実装されている形式となっております．

なお，｢もっと簡単にノード間を接続できるように改善｣とございますが，具体的に，どのような操作方法とすれば良いのでしょうか？

こちらの外部ライブラリは，バイナリ形式で提供されている部分もあるため，全てに手を加える事はできないのですが，ご提案頂いた方法を基に，修正を行えるか確認を行わせて頂きます．

**Comment by ga-sakamoto** [comment]
FSMEditorの操作ですが，アイコンの形状と緑の枠線で，操作状態を確認する事ができます．

まず，遷移を開始する状態につきましては，
　アイコンが指の形状で，対象状態が緑の枠で囲まれている位置では，遷移を追加するモード
　アイコンが上下左右の矢印で，対象状態に枠が表示されていない場合には，対象ノードの位置を移動するモード
となります．
遷移先のノードにつきましては，マウスをドラッグした状態で，
　接続先の状態に緑の枠線が表示された状況ですと，対象状態に遷移が接続
　対象状態に緑の枠線が表示されていない場合には，マウスを放した位置に新規状態が追加
されます．

ただ，遷移を開始する状態について，当たり判定が厳しい，とのご意見を頂きましたので，ノード名のラベルフォントを拡大し，もう少し遷移作成の操作を開始しやすく修正します．
