### ISSUE TITLE
[RTSE]RTC強制終了、再起動直後にネームサービスビューのRTCを選択するとフリーズする

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#5]
**Describe the bug**
RTCのプロセスを強制終了した直後にネームサービスビューのRTCを選択するとフリーズすることがある。

**To Reproduce**
1. RTCを強制終了する
2. RTCを再起動する
3. ネームサービスビューのRTCを選択する
4. RTSEがフリーズする

**Reproducibility**
以下の状態で発生しやすい傾向がある。

- 2つ以上のRTCを強制終了、再起動する
- 再起動直後に、ネームサービスビューで片方のRTCがゾンビ状態、片方は正常に表示されている状況でRTCを選択する

**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 1.2

**Additional context**

**Comment by ga-sakamoto** [comment]
こちらのお話なのですが，現象を再現できておりません．
#12 の修正時に，CORBAのタイムアウト周りも色々と修正させて頂きましたため，現状の最新版でも症状が発生するかを再度ご確認頂けませんでしょうか？
ご面倒をお掛けしてしまい，たいへん申し訳ございませんが，よろしくお願いいたします．

**Comment by Nobu19800** [comment]
RELENG_1_2のソースコードで試してみたのですが、問題が発生しています。
原因は不明ですが、C++のRTCよりもPythonのRTCで試した方が発生の頻度が高いです。

以下がフリーズしている状態の画面ですが、ネームサービスビューのConsoleIn0.rtcをクリックすると25秒ほどフリーズします。その後に右側にRTCの情報は表示されることもありません。何回クリックしてもこの状態です。

ConsoleIn0.rtcは別に起動したRTSEでは正常にプロファイルを取得できています。

![image](https://user-images.githubusercontent.com/6216077/53307241-b9eebb80-38d9-11e9-9b4d-828121277647.png)

更新ボタンを押すと正常な状態に戻るようです。
