### ISSUE TITLE
独自データ型のポートを持つJavaのRTCがビルドエラーになる

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#500]
**Describe the bug**
RTCBuilderにおいて、モジュール名が定義されている独自データ型のポートを定義したRTCのビルドが通らない

**To Reproduce**
https://openrtm.org/openrtm/ja/doc/developersguide/dataport_advanced
この方法で独自データ型のデータポートを定義し、Javaのコードを生成する。

**Reproducibility**
100%

**Expected behavior**
- コード生成後、Javaのパースペクティブに切り替わった際、以下のエラーが出る
  - インポートされたMyModuleは見つかりません
    - import MyModule.MyData; で発生
    - このため、「MyDataを型に解決できません」となっていると思われる

**Environment**
 - OS: Windows10
 - OpenRTM-aist Version 2.0.0

**Additional context**
- 独自データ型を利用しているRTCのビルドが通るようにする設定、手順等を教えて頂きたく、下記の動作も報告します
- この状態で、build_***.xml をantでビルドすると以下のエラーになる
```
Cannot run program "C:\Program Files\OpenRTM-aist\2.0.0\jre\..\bin\idlj"  指定されたファイルが見つかりません。
```
- このパスは、build_***.xmlの下記によるものと理解です
```
<exec executable="${java.home}/../bin/idlj">
```
- JDK8はAdoptium（旧AdoptOpenJDK）でインストールしており、OpenRTPのインストール済みJREに追加してチェックを入れています
  - C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot
  - インストール済みJRE画面で、「jdk-8.0.302.8-hotspot（デフォルト）」となっている
- JDK8をインストールした際にシステム環境変数のJAVA_HOMEが設定されているので、これを利用するように書き換えてみるとidlcompile処理は進みますが、「エラー: この文字は、エンコーディングUTF8にマップできません」が出ます。元々MyData型のエラーが出ていたので意味ない確認かもしれませんが。
```
<exec executable="${env.JAVA_HOME}/bin/idlj">
```

**Comment by n-ando** [comment]
@n-kawauchi さんへ
Linuxでの挙動がわかったら、ここに記載して坂本さんと情報共有してください。

**Comment by n-kawauchi** [comment]
@ga-sakamoto さん、このIssueでは２つの問題を報告しています。
- １）独自データ型（モジュール名：MyModule）を利用した際に、インポートされたMyModuleが見つからないとなるエラー
  - WindowsでもLinuxでも発生します。私には原因が分かりません。
- ２）Windows環境でのみidljが見つからずidlcompileが通らない
  - 原因は、build_***.xml内のidlcompileで定義している下記コードです。
  ```
  <exec executable="${java.home}/../bin/idlj">
  ```
  - Windows + Adoptium（旧AdoptOpenJDK）の環境で、OpenRTPと関係ないディレクトリで${java.home}のパスを調べると以下になりました。このことだけでもWindowsの場合は上記パスではidljが見つかりません。
  ```
  java.home=C:\Program Files\Eclipse Foundation\j...
  （これは、C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot のこととの理解です）
  ```
  - ところが、OpenRTP上でantによりRTCをビルドすると、OpenRTPを起動するbatファイルの1行目で、「set PATH=%RTM_ROOT%jre\bin;%PATH%」としているため、${java.home}のパスが下記になっているとの理解です。
  ```
  [echo] java.home : C:\Program Files\OpenRTM-aist\2.0.0\jre
  ```
  - このため、Windows環境では${java.home}は利用できない。AdoptiumをインストールしたらJAVA_HOMEが定義されたのでこれを利用したらよいのではと考えました。この場合、以下となります。
  ```
  <exec executable="${env.JAVA_HOME}/bin/idlj">
  ```
  - antでOSを検出し、プロパティを設定することが可能なようです。それを利用してOS別に idlj を指定するようにしたらどうかと考えてみました。いかがでしょうか。

**Comment by n-kawauchi** [comment]
@ga-sakamoto さん、エラーの原因は  build_***.xml の設定2か所でした。
- Windows環境でidljのパスが見つからない
  - oracle JDK8の無償版はサポートが終了しているため、他ベンダのJDKを利用するとパスが異なるため見つからない
  - JAVA_HOMEを利用するようにした
- UbuntuでのRTM2.0系はシステム環境変数名が RTM_IDL_DIR2 に変更になっているためidlファイルが見つからない

antでOSを判定してWindows, Unix(Linux) それぞれでプロパティを設定することで対応するようにしました。
RTCBが生成したbuild_ModuleName.xmlに修正を加えたものup-build_ModuleName.xmlを添付します。
よろしくお願いします。
[build_ModuleName.xml.txt](https://github.com/OpenRTM/OpenRTP-aist/files/10291610/build_ModuleName.xml.txt)
[up-build_ModuleName.xml.txt](https://github.com/OpenRTM/OpenRTP-aist/files/10291612/up-build_ModuleName.xml.txt)

**Comment by ga-sakamoto** [comment]
@n-kawauchi さん
色々とご確認，ご調査頂き，ありがとうございます．
また，こちらでの調査などが遅れてしまっており，たいへん申し訳ございませんでした．
ひとまず，ご連絡を頂きました内容でコード生成するように修正させて頂きます．
