### ISSUE TITLE
OpenRTM2.0の環境でPython RTCのidlcompile.shがエラーになる

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#501]
**Describe the bug**
- OpenRTM2.0系のみがインストールされている環境での不具合
- RTCBuilderで独自データ型idlを利用しているPython RTCを生成、cmake buildすると エラーになる
- 原因は、idlcompile.shにOpenRTM1.2系のコマンドが記述されているためコマンドが見つからない
- 2.0系のコマンド名に修正する。「rtm-config」->「rtm2-config」

**Reproducibility**
100%

**Environment**
 - OS: Ubnutn 20.04
 - OpenRTM-aist Version 2.0.0

**Comment by n-ando** [comment]
/jp.go.aist.rtm.rtcbuilder.python/src/jp/go/aist/rtm/rtcbuilder/python/template/python/idlcompile.sh.vsl
を以下のように変更。


```sh
#/bin/bash

RTM_CONFIG="rtm2-config"
if type "rtm-config" > /dev/null 2>&1; then
    RTM_CONFIG_CMD="rtm-config"
fi
if type "rtm-config2" > /dev/null 2>&1; then
    RTM_CONFIG_CMD="rtm-config2"
fi
if type "rtm2-config" > /dev/null 2>&1; then
    RTM_CONFIG_CMD="rtm2-config"
fi
if test "x$RTM_CONFIG_CMD" = "x" ; then
    echo "rtm-config/rtm-config2/rtm2-config command not found."
    exit 1
fi
IDL_PATH=`$RTM_CONFIG_CMD --rtm-idldir`
echo omniidl -bpython -I$IDL_PATH #foreach($IdlFile in ${allIdlFileParamBuild})idl/${IdlFile.IdlFile} #end

```

**Comment by ga-sakamoto** [comment]
たいへん失礼いたしました．
再度，修正させて頂きました．
