### ISSUE TITLE
UbuntuでRTC BuilderがRTC.xmlをインポートした場合に、IDLファイルのパスが正常に設定されない問題

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#511]
**Describe the bug**
UbuntuでRTC BuilderがRTC.xmlをインポート後にコード生成しようとするとエラーになる。

**To Reproduce**
1. 以下のRTC.xmlを作成する。
[RTC.xml.txt](https://github.com/OpenRTM/OpenRTP-aist/files/12460123/RTC.xml.txt)
2. RTC BuilderでRTC.xmlをインポートする
3. コード生成ボタンを押す
![rtcbuilderidl2](https://github.com/OpenRTM/OpenRTP-aist/assets/6216077/93d7db79-9353-4598-8f8b-84d57d2d75a1)

**Reproducibility**
100%

**Expected behavior**
正常にコード生成できるようにする。

**Screenshots or Logs**

**Environment**
 - OS: Ubuntu 22.04
 - OpenRTM-aist 2.0

**Additional context**

**Comment by n-ando** [comment]
PR->Mergedしましたのでcloseします。
