### ISSUE TITLE
UbuntuのRTC Builderにより生成したRTC.xmlを、WindowsのRTC Builderでインポートした場合の問題

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#512]
**Describe the bug**
Ubuntuで起動したRTC BuilderでRTC.xmlを作成後、WIndowsで起動したRTC Builderでインポートした場合に、IDLファイルのパスの区切り文字の違いによりロードできない。

**To Reproduce**
1. Ubuntuで以下のRTC.xmlを作成する。
[RTC.xml.txt](https://github.com/OpenRTM/OpenRTP-aist/files/12460123/RTC.xml.txt)
2. WindowsでRTC Builderを起動する
3. RTC BuilderでRTC.xmlをインポートする
![image](https://github.com/OpenRTM/OpenRTP-aist/assets/6216077/55a08d1e-a5e1-452f-95aa-14271e75875c)

**Reproducibility**
100%

**Expected behavior**
WindowsでIDLファイルのパスをスラッシュで区切った文字列でRTC.xmlを保存して、インポートする時にはスラッシュとバックスラッシュを区別せずにIDLファイルの存在確認、読み込みができるようにする。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 2.0

**Additional context**

**Comment by ga-sakamoto** [comment]
申し訳ございません．
ご連絡を頂きましたRTC.xmlを使用して，こちらの環境で試してみた所，正常にインポート，コード生成を行う事ができました．

ご確認なのですが，ご使用になられたWindows環境では，環境変数RTM_ROOTは設定されておりますでしょうか？
エラー内容を拝見した所，タグ<RTM_ROOT>をパスに変換できていないように思いましたので，ご確認させて頂きました．

**Comment by Nobu19800** [comment]
#513 の修正前の場合、`<RTM_ROOT>\`の文字列を環境変数RTM_ROOTと置き換えるので、`<RTM_ROOT>/rtm/idl`の文字列では置き換えが行われずにエラーになります。#513 で解決するようですので、このissueは閉じます。
