### ISSUE TITLE
*[RTCB]Windows用cpackテンプレートのアーキテクチャ名取得変数変更

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#530]
**Is your feature request related to a problem? Please describe.**
- 生成するmsiファイル名に含めているアーキテクチャはCPACK_SYSTEM_NAMEの値を利用している
- 現状、CPACK_SYSTEM_NAMEの値は「win64」or「win32」のみサポートされている
- OpenRTMは64bit環境のみ対応のためmsiファイル名は次のようになる
testInPort100_rtm202_win64.msi
- 今後OpenRTMのインストーラがarm64のWindows環境にも対応した場合、Intel , AMD環境用のmsiと区別できない

**Describe the solution you'd like**
- CMAKE_SYSTEM_PROCESSORの値は、システム環境変数のPROCESSOR_ARCHITECTURE値が設定されるとのこと
- Intel , AMD環境ではPROCESSOR_ARCHITECTUREの値が amd64 となっている
- これまでIntel , AMD環境用のアーキテクチャ名は、x86_64 を利用してきたので、下記の処理で実現できそう
```
if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "AMD64")
  set(CPACK_ARCH "x86_64")
else()
  set(CPACK_ARCH "arm64")
endif()
```

**Additional context**
- arm64のWindows環境での動作確認後に、上記コードを挿入する具体的な修正箇所を追記する

**Comment by n-ando** [comment]
@n-kawauchi さん、Cmakeの修正点をissueに詳しく挙げてください。

**Comment by n-kawauchi** [comment]
C++, Python, Java, Luaの各言語用テンプレートを以下のように修正して下さい。
このIssue本来の修正に加え、cmake実行時のワーニング対応、CPackでの Wixtoolset v5 対応も合わせて行う。

- 一番トップのCMakeLists.txt修正（4言語共通修正）
  - cmake_minimum_requiredで指定しているバージョン 3.5.1 を 3.16 に変更
    - Luaはバージョンが 2.8となっていているが、これも 3.16 にする
    - 変更理由は、3.5.1にしていると cmake 3.31 で赤字で下記メッセージが出るため
      ```
      Compatibility with CMake < 3.10 will be removed from a future version of CMake.
      ```
  - CPACK_ARCH設定追加
      ```
      if(WIN32)
            ：
      else(WIN32)
        set(OPENRTM_SHARE_PREFIX "share/openrtm-${OPENRTM_VERSION_MAJOR}.${OPENRTM_VERSION_MINOR}")
        set(INSTALL_PREFIX "${OPENRTM_SHARE_PREFIX}/components/${PROJECT_TYPE}/${PROJECT_NAME}")
      endif(WIN32)
      この後に下記を追加

      if(${CMAKE_SYSTEM_PROCESSOR} MATCHES "AMD64")
        set(CPACK_ARCH "x86_64")
      else()
        set(CPACK_ARCH "arm64")
      endif()
      ```
- cmake/cpack_options.cmake.in（4言語共通修正）
  - CMakeLists.txtで追加した CPACK_ARCH の設定
    ```
    IF (WIN32)
      set(CPACK_GENERATOR "WIX")
        ：
      set(CPACK_PACKAGE_FILE_NAME
          "@PROJECT_NAME@@PROJECT_SHORT_VER@_rtm@RTM_SHORT_VER@_${CPACK_SYSTEM_NAME}")

      この行の ${CPACK_SYSTEM_NAME} を @CPACK_ARCH@ に変更する
    ```
  - WixToolset v5対応
    - set(CPACK_WIX_VERSION 4)　を定義する
    - 現時点でwixをインストールすると自動でv5がインストールされるが、v4の記述で問題なくv5で動作する
    - v5だからと、set(CPACK_WIX_VERSION 5) とすると動作しない
      ```
      IF (WIN32)
        set(CPACK_GENERATOR "WIX")
        set(CPACK_WIX_VERSION 4)　　　<-- ここへ追加する
      ```

- Luaのみのバグ修正
  - 一番トップのCMakeLists.txtの下記コード（2か所）を削除する
    ```
    if(POLICY CMP0040)
      cmake_policy(SET CMP0040 OLD)
    endif()
    if(POLICY CMP0053)
      cmake_policy(SET CMP0053 OLD)
    endif()
    ```
    ```
    foreach(target ${EXEC_FILES})
      add_custom_command( TARGET ${PROJECT_NAME} POST_BUILD
          COMMAND ${CMAKE_COMMAND} -E copy
          ${PROJECT_SOURCE_DIR}/${target} ${PROJECT_BINARY_DIR}
      )
    endforeach()
    ```
  - src/CMakeLists.txt　・・・srcディレクトリごと削除する
