### ISSUE TITLE
MANIFEST.MFファイルに記載しているOpenRTPのバージョン番号について

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#60]
master, RELENG_1_2ソースのバージョン番号更新に関して、確認させて下さい。

リポジトリに登録している各MANIFEST.MFファイルのバージョン番号を今後更新しないようにしたいと考えておりますが、この対応で影響は無いでしょうか？

Linux環境でのantによるビルド時、MANIFEST.MF内のバージョン番号をビルドした日付を加えたもの「1.2.0.v20190308」等に置き換えています。よって、現在のMANIFEST.MFのバージョン番号は
1.2.0となっておりますが、このまま更新しません。

Windows環境でbuild.xmlを使用せずにビルドされているとお聞きしておりますので、影響について気になりました。　よろしくお願いいたします。

**Comment by ga-sakamoto** [comment]
ご連絡ありがとうございます．
上記のお話ですが，こちらには影響はございません．
開発を行っている際には，Jarファイルの作成は行っておらず，Eclipse上でそのまま動作させているためです．

**Comment by n-kawauchi** [comment]
了解しました。
jarファイルを生成されないということでしたら、今後、MANIFEST.MFはテンプレートファイル（MANIFEST.MF.in）をgitで管理し、antでビルドする際にバージョン番号を埋め込んだMANIFEST.MFを生成する方向で検討したいと考えております。この対応はバージョン2.0で試す予定です。1.2.1では現状のMANIFEST.MFファイルをそのまま利用します。
ありがとうございました。

**Comment by ga-sakamoto** [comment]
上記のお話なのですが，通常はMANIFEST.MFは存在せず，antでビルドを行わないとMANIFEST.MFが生成されない形となるのでしょうか？
こちらではJarファイルの作成は行っていないのですが，MANIFEST.MF自体は参照しております．このため，もしもantでビルドを行わないとMANIFEST.MFが生成されない形になってしまうと，Eclipse起動時にエラーとなってしまいます．
そうではなく，現状のようにMANIFEST.MFは存在し，antビルド時にバージョン番号だけ書き換える形であれば問題ありません．

**Comment by n-kawauchi** [comment]
そうなのですね、了解しました。
現状の、antでのビルド時にMANIFEST.MFを書き換えると、git statusで変更を確認した時にバージョン管理下のMANIFEST.MF（14ファイル）も変更ありとなってしまい、実際に修正したファイルの確認がしづらいという思いからテンプレートファイル化しようと考えました。
MANIFEST.MFは現在のバージョン番号(1.2.0)のままの状態で残します。
お手数をおかけいたしました。
