### ISSUE TITLE
[RTSE]OpenRTM-aist-1.1.2付属のEdgeコンポーネントを起動し，カメラコンポーネントと接続すると，システムエディタ上の表示がおかしくなってしまう

### ISSUE THREAD

**Issue by ga-sakamoto** [OpenRTM/OpenRTP-aist#73]
1.1.2のEdgeコンポーネントは，カメラと接続するとバッファオーバーフローでCORBA自体が異常終了してしまうが，この時，RTSEの表示がおかしくなってしまう．

**Comment by ga-sakamoto** [comment]
上記の現象を再現できておりません．このため，もしも上記の現象が発生した場合には，RTSEのログ情報をお送り頂けませんでしょうか？
RTSEのログ情報は，RCP版RTSEの場合，ユーザのホームディレクトリ直下の｢openrtp.log｣というファイルに出力されています．

**Comment by Nobu19800** [comment]
この問題はWindowsでインストーラーによりインストールした場合、理由はよく分かりませんがOpenCVのコンポーネントを原因となる機能が含まれていない状態でビルドした実行ファイルが入るため再現しなかったはずです。Ubuntuのdebパッケージでインストールした場合は発生します。

以下のEdgeComp.exeであれば問題は再現できます。


- [edge.zip](https://github.com/OpenRTM/OpenRTP-aist/files/3225910/edge.zip)

**Comment by ga-sakamoto** [comment]
情報ありがとうございます．
お送り頂きましたコンポーネントを使用して，再度，試してみたいと思います．

**Comment by ga-sakamoto** [comment]
RTCを構成するCORBAリモートオブジェクト(ComponentProfile，RTObject，ExecutionContextなど)のいずれかが例外を返してきた場合，対象RTC全体を削除するようにとりあえず修正する．
