### ISSUE TITLE
[RTCB]データ型にImg型またはJARA_ARM型を指定したC++版RTCがビルドエラーになる

### ISSUE THREAD

**Issue by n-kawauchi** [OpenRTM/OpenRTP-aist#79]
**Describe the bug**
- データポートのデータ型に「JARA_ARM::TimedJointPos」を指定してC++ RTCを生成し、ビルドすると下記エラーになります。
```
'ULONG' : あいまいなシンボルです。
```
- 上記は、ヘッダーファイルの下記namespace文をコメントアウトすればビルドが通ります
```
using namespace JARA_ARM;
```

- データポートのデータ型に「Img::CameraDeviceProfile」を指定してC++ RTCを生成し、ビルドすると下記エラーになります。このエラーの対応方法は分かっておりません。
```
3>C:\Program Files\OpenRTM-aist\1.2.0\rtm/Timestamp.h(40): error C2039: 'tm' : 'Img::CameraDeviceProfile' のメンバーではありません。
3>          c:\program files\openrtm-aist\1.2.0\rtm\idl\CameraCommonInterface.hh(456) : 'Img::CameraDeviceProfile' の宣言を確認してください。
```

**Reproducibility**
vc2010とvc2015環境で同じエラーになることを確認

**Environment**
 - OS: Windows10
 - OpenRTM-aist Version 1.2.0

**Comment by Nobu19800** [comment]
OpenRTM-aist 1.2からタイムスタンプのないデータ型は使えなくなったはずなので`Img::CameraDeviceProfile`でエラーになるのは仕方ないです。Timedが付かないVelocity2D型等でもエラーになります。

**Comment by ga-sakamoto** [comment]
サービスインターフェースにJARA_ARM型を指定した場合，生成されたコードの各メソッドの戻り値がポインタ型となっていない
