### ISSUE TITLE
RTSEでActivate Systemsボタン等が表示されない

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#88]
**Describe the bug**
RTSystemEditorを起動したときにActivate Systemsボタン等が表示されない場合がある。

**To Reproduce**
1. OpenRTM-aistをインストールする
2. OpenRTPを起動する
3. RTSystemEditorを起動する

問題が発生するのはインストール後に初めて起動する場合のみであり、OpenRTPを再起動すると一応は解決する。

**Reproducibility**
おおよそ20％

**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 1.2

**Additional context**

**Comment by n-ando** [comment]
@ga-sakamoto さん。
メニューボタンの表示順問題解消のため、#88はいったん戻します。
ユーザに再起動を促すダイアログを表示することで、本件は対処することにした。
修正よろしくお願いいたします。

**Comment by n-kawauchi** [comment]
Activate Systemsボタン等が表示されないケースについての補足情報です。
#338 の動作確認の結果、OpenRTPを起動する場合に新規のworkspaceを指定した場合と、RCP版RTSEを始めて起動する場合は、100%再現します。つまり、Activate Systemsボタン等が表示されません。

RCP版RTSEは、スタートメニューのショートカットでworkspaceを「-data %TEMP%\rtse」と指定しています。
ユーザがこのrtseディレクトリを削除することは考えなくてよいと思いますが、削除後に起動すれば、ボタンが表示されない状況を再現できます。

**Comment by n-kawauchi** [comment]
@ga-sakamoto さん

> ユーザに再起動を促すダイアログを表示することで、本件は対処することにした。

作業中でしたら申し訳ございません。この修正を1.2.2 版に反映させるとのことですので、対応、よろしくお願いします。
