### ISSUE TITLE
コード生成時にConfiguration Set Parameterの名称は半角英数字を入力してください」とエラーメッセージが出る

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#89]
**Describe the bug**
RTCBでコンフィギュレーションパラメータを設定後にコード生成を行うと「Configuration Set Parameterの名称は半角英数字を入力してください」とエラーメッセージが出る場合がある。
何回確認しても半角英数字しか入力されておらず、名前を入力しなおしても解決しない。
何故かOpenRTPを再起動すると解決した。

**To Reproduce**
1. RTCBuilderを起動する
2. コンフィギュレーションパラメータを設定する
3. コード生成をする

**Reproducibility**
1％
ROBOMECH2019の講習会で初めて問題を確認した。それ以前は発生したことがなかったため、問題の発生条件などは不明。

**Expected behavior**

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 1.2.0

**Additional context**

**Comment by n-ando** [comment]
再現できないので、とりあえずクローズします。
また減少が出るようなら再オープン。
