### ISSUE TITLE
EventInPortを持つRTCのビルドでエラーが発生する

### ISSUE THREAD

**Issue by Nobu19800** [OpenRTM/OpenRTP-aist#97]
**Describe the bug**
#87 の変更がEventInPortについては修正していないためエラーが発生する。

**To Reproduce**
1. RTC BuilderでFSMを有効にしてC++でコード生成
2. Visual Studioでビルドする

**Reproducibility**
100％

**Expected behavior**
`EventInPort`ではなく`RTC::EventInPort`に修正する必要がある。

**Screenshots or Logs**

**Environment**
 - OS: Windows 10
 - OpenRTM-aist 2.0
 - ...

**Additional context**

**Comment by ga-sakamoto** [comment]
こちらのお話なのですが，FSMコンポーネントのコードにつきましては，再度，大幅に見直す予定となっております(#71)．
このため，今回のご指摘内容につきましては，こちらを修正する際に，併せて修正させて頂く形とさせて頂ければ幸いです．
(#71 の内容には追記させて頂きました)
